-- POPULAR A TABELA MC_DEPTO INSERINDO NO MINIMO 7 DEPARTAMENTOS

INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'COMERCIAL', 'A');
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'CONTABILIDADE', 'A');
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'ESTOQUE', 'A');
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'FINANCEIRO', 'A');
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'SERVIÇO DE ATENDIMENTO AO CLIENTE - SAC', 'A');
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'RECURSOS HUMANOS - RH','A');
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'LOGISTICA', 'A');
