-- a) Para essa etapa de instruções DML, analise as recomendações abaixo e para cada solicitação,
-- escreva a instrução SQL que resolva as ocorrências abaixo: Comercial, Contabilidade, Estoque, Financeiro, SAC, Recursos Humanos, Logística.

--Inserindo o Departamento Comercial
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
    VALUES (SQ_MC_DEPTO.NEXTVAL, 'COMERCIAL', 'A');

--Inserindo o Departamento Contabilidade
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
    VALUES (SQ_MC_DEPTO.NEXTVAL, 'CONTABILIDADE', 'A');

--Inserindo o Departamento Estoque
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
    VALUES (SQ_MC_DEPTO.NEXTVAL, 'ESTOQUE', 'A');

--Inserindo o Departamento Financeiro
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
    VALUES (SQ_MC_DEPTO.NEXTVAL, 'FINANCEIRO', 'A');

--Inserindo o Departamento Servico de Atendimento ao cliente - SAC
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
    VALUES (SQ_MC_DEPTO.NEXTVAL, 'SERVICO DE ATENDIMENTO AO CLIENTE - SAC', 'A');

--Inserindo o Departamento Recursos Humanos - RH
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
    VALUES (SQ_MC_DEPTO.NEXTVAL, 'RECURSOS HUMANOS - RH','A');

--Inserindo o Departamento Logistica
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
    VALUES (SQ_MC_DEPTO.NEXTVAL, 'LOGISTICA', 'A');

COMMIT;

-- b) Popular a tabela FUNCIONARIO, inserindo no mínimo 3 (três) funcionários para cada departamento criado.

--Inserindo 4 funcionarios no departamento comercial(3) 
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 3, 1,'Adriana Arantes',TO_DATE('12/04/83', 'DD/MM/YY'), NULL, NULL,'GERENTE COMERCIAL', 11433, NULL, NULL, TO_DATE('15/02/08', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 3, SQ_MC_FUNCIONARIO.CURRVAL-1,'Juliana Montenegro',TO_DATE('21/09/00', 'DD/MM/YY'), NULL, NULL,'ANALISTA COMERCIAL', 6800, NULL, NULL, TO_DATE('15/02/23', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 3, SQ_MC_FUNCIONARIO.CURRVAL-2,'Karina Salgueiro',TO_DATE('17/01/90', 'DD/MM/YY'), NULL, NULL,'ANALISTA COMERCIAL', 7800, NULL, NULL, TO_DATE('15/02/23', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 3, SQ_MC_FUNCIONARIO.CURRVAL-3,'Rubens Monte',TO_DATE('04/12/95', 'DD/MM/YY'), NULL, NULL,'ANALISTA COMERCIAL', 6800, NULL, NULL, TO_DATE('15/02/23', 'DD/MM/YY'), NULL);


--Inserindo 4 funcionarios no departamento de contabilidade(4)
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 4, 1,'Geraldo Albuquerque',TO_DATE('11/07/85', 'DD/MM/YY'), NULL, NULL,'GERENTE CONTABILIDADE', 10400, NULL, NULL, TO_DATE('15/02/05', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 4, SQ_MC_FUNCIONARIO.CURRVAL-1,'Ricardo Santos',TO_DATE('18/11/00', 'DD/MM/YY'), NULL, NULL,'ANALISTA CONTABIL', 5800, NULL, NULL, TO_DATE('15/02/23', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 4, SQ_MC_FUNCIONARIO.CURRVAL-2,'Mariana Vargas',TO_DATE('28/10/95', 'DD/MM/YY'), NULL, NULL,'ANALISTA CONTABIL', 6300, NULL, NULL, TO_DATE('15/02/23', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 4, SQ_MC_FUNCIONARIO.CURRVAL-3,'Ana Luisa Vieira',TO_DATE('08/06/96', 'DD/MM/YY'), NULL, NULL,'ANALISTA CONTABIL', 6389, NULL, NULL, TO_DATE('18/02/21', 'DD/MM/YY'), NULL);


--Inserindo 4 funcionarios no departamento de Estoque(5)
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 5, 1,'Mateus Luchesse',TO_DATE('24/05/86', 'DD/MM/YY'), NULL, NULL,'GERENTE ESTOQUE', 10400, NULL, NULL, TO_DATE('15/02/10', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 5, SQ_MC_FUNCIONARIO.CURRVAL-1,'Karla Andrade',TO_DATE('02/08/96', 'DD/MM/YY'), NULL, NULL,'ANALISTA ESTOQUE', 6300, NULL, NULL, TO_DATE('11/02/18', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 5, SQ_MC_FUNCIONARIO.CURRVAL-2,'Leonardo Sakagushi',TO_DATE('28/11/93', 'DD/MM/YY'), NULL, NULL,'ANALISTA ESTOQUE', 6300, NULL, NULL, TO_DATE('07/02/17', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 5, SQ_MC_FUNCIONARIO.CURRVAL-3,'Carolina Abrantes',TO_DATE('22/09/90', 'DD/MM/YY'), NULL, NULL,'ANALISTA ESTOQUE', 6540, NULL, NULL, TO_DATE('15/02/14', 'DD/MM/YY'), NULL);


--Inserindo 4 funcionarios no departamento de financeiro(6)
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 6, 1,'Roberta Branco',TO_DATE('09/02/85', 'DD/MM/YY'), NULL, NULL,'GERENTE FINANCEIRO', 12940, NULL, NULL, TO_DATE('16/02/09', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 6, SQ_MC_FUNCIONARIO.CURRVAL-1,'Fernando Soares',TO_DATE('17/11/89', 'DD/MM/YY'), NULL, NULL,'ANALISTA FINANCEIRO', 7200, NULL, NULL, TO_DATE('25/02/09', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 6, SQ_MC_FUNCIONARIO.CURRVAL-2,'Tulio Heguer',TO_DATE('14/03/90', 'DD/MM/YY'), NULL, NULL,'ANALISTA FINANCEIRO', 6900, NULL, NULL, TO_DATE('21/06/12', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 6, SQ_MC_FUNCIONARIO.CURRVAL-3,'Camila Scavuzzi',TO_DATE('04/07/88', 'DD/MM/YY'), NULL, NULL,'ANALISTA FINANCEIRO', 7300, NULL, NULL, TO_DATE('25/02/09', 'DD/MM/YY'), NULL);


--Inserindo 4 funcionarios no departamento de SAC(7)
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 7, 1,'Eduardo Melo',TO_DATE('08/01/85', 'DD/MM/YY'), NULL, NULL,'GERENTE ATENDIMENTO AO CLIENTE', 11600, NULL, NULL, TO_DATE('09/04/10', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 7, SQ_MC_FUNCIONARIO.CURRVAL-1,'Beatriz Mendonca',TO_DATE('17/11/86', 'DD/MM/YY'), NULL, NULL,'ANALISTA ATENDIMENTO AO CLIENTE', 6900, NULL, NULL, TO_DATE('07/03/10', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 7, SQ_MC_FUNCIONARIO.CURRVAL-2,'Clarice Santos',TO_DATE('03/08/90', 'DD/MM/YY'), NULL, NULL,'ANALISTA ATENDIMENTO AO CLIENTE', 6580, NULL, NULL, TO_DATE('08/09/15', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 7, SQ_MC_FUNCIONARIO.CURRVAL-3,'Arthur Rizzo',TO_DATE('13/12/90', 'DD/MM/YY'), NULL, NULL,'ANALISTA ATENDIMENTO AO CLIENTE', 6580, NULL, NULL, TO_DATE('08/09/18', 'DD/MM/YY'), NULL);


--Inserindo 4 funcionarios no departamento de RH(8)
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 8, 1,'Paula Ximenes',TO_DATE('05/05/80', 'DD/MM/YY'), NULL, NULL,'GERENTE RECURSOS HUMANOS', 11980, NULL, NULL, TO_DATE('02/01/05', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 8, SQ_MC_FUNCIONARIO.CURRVAL-1,'Maria Julia Gouveia',TO_DATE('04/02/99', 'DD/MM/YY'), NULL, NULL,'ANALISTA RECURSOS HUMANOS', 6300, NULL, NULL, TO_DATE('08/09/22', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 8, SQ_MC_FUNCIONARIO.CURRVAL-2,'David Alves',TO_DATE('13/05/93', 'DD/MM/YY'), NULL, NULL,'ANALISTA RECURSOS HUMANOS', 6300, NULL, NULL, TO_DATE('02/01/00', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 8, SQ_MC_FUNCIONARIO.CURRVAL-3,'Gustavo Fazio',TO_DATE('04/02/95', 'DD/MM/YY'), NULL, NULL,'ANALISTA RECURSOS HUMANOS', 6300, NULL, NULL, TO_DATE('02/01/00', 'DD/MM/YY'), NULL);


--Inserindo 4 funcionarios no departamento de Logistica(9)
INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 9, 1,'Murilo Souza',TO_DATE('09/08/83', 'DD/MM/YY'), NULL, NULL,'GERENTE LOGISTICA', 11980, NULL, NULL, TO_DATE('02/01/05', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 9, SQ_MC_FUNCIONARIO.CURRVAL-1,'Regina Furtado',TO_DATE('02/05/88', 'DD/MM/YY'), NULL, NULL,'ANALISTA LOGISTICA', 6300, NULL, NULL, TO_DATE('02/01/06', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 9, SQ_MC_FUNCIONARIO.CURRVAL-2,'Gabriela Nakamura',TO_DATE('12/02/84', 'DD/MM/YY'), NULL, NULL,'ANALISTA LOGISTICA', 6300, NULL, NULL, TO_DATE('02/01/06', 'DD/MM/YY'), NULL);

INSERT INTO MC_FUNCIONARIO(CD_FUNCIONARIO, CD_DEPTO, CD_GERENTE, NM_FUNCIONARIO, DT_NASCIMENTO, FL_SEXO_BIOLOGICO,DS_GENERO, DS_CARGO, VL_SALARIO, DS_EMAIL, ST_FUNC, DT_CADASTRAMENTO, DT_DESLIGAMENTO) 
    VALUES (SQ_MC_FUNCIONARIO.NEXTVAL, 9, SQ_MC_FUNCIONARIO.CURRVAL-3,'Maria Evans',TO_DATE('22/08/85', 'DD/MM/YY'), NULL, NULL,'ANALISTA LOGISTICA', 6300, NULL, NULL, TO_DATE('02/01/06', 'DD/MM/YY'), NULL);

COMMIT;

-- c) Parte 1: POPULAR A TABELA MC_ESTADO COM TODOS OS ESTADOS DO BRASIL

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('AC','Acre');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('AL','Alagoas');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('AP','Amapa');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('AM', 'Amazonas');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('BA', 'Bahia');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('CE', 'Ceara');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('ES', 'Espirito Santo');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('GO', 'Goias');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('MA', 'Maranhao');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('MT', 'Mato Grosso');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('MS', 'Mato Grosso do Sul');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('MG', 'Minas Gerais');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('PA', 'Para');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('PB', 'Paraiba');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('PR', 'Parana');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('PE', 'Pernambuco');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('PI', 'Piaui');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('RJ', 'Rio de Janeiro');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('RN', 'Rio Grande do Norte');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('RS', 'Rio Grande do Sul');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('RO', 'Rondonia');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('RR', 'Roraima');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('SC', 'Santa Catarina');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('SP', 'Sao Paulo');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('SE', 'Sergipe');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('TO', 'Tocantins');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('DF', 'Distrito Federal');

COMMIT;

--c) Parte 2: POPULAR A TABELA MC_CIDADE ASSOCIANDO NO MiNIMO 2 CIDADES PARA 
--CADA UM DOS 5 ESTADOS SELECIONADOS

--Inserindo 3 cidades no estado de Sao Paulo
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'SP', 'CAMPINAS', 3509502, 19);

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'SP', 'SAO JOSE DOS CAMPOS', 3549904, 12);

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'SP', 'RIBEIRAO PRETO', 3543402, 16);

--Inserindo 3 cidades no estado de Minas Gerais
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'MG', 'UBERLANDIA', 3170206, 34);

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'MG', 'BELO HORIZONTE', 3106200, 31);

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'MG', 'JUIZ DE FORA', 3136702, 32);

--Inserindo 3 cidades no estado de Pernambuco
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'PE', 'CARUARU', 2604106,81);

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'PE', 'RECIFE', 2611606,81);

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'PE', 'PETROLINA', 2611101,87);

--Inserindo 3 cidades no estado de Rio Grande do Norte
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'RN', 'NATAL', 2408102, 84);

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'RN', 'MOSSORO',2408003, 84);

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'RN', 'PARNAMIRIM', 2403251, 84);

--Inserindo 3 cidades no estado de Santa Catarina
INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'SC', 'JOINVILLE', 4209102, 47);

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'SC', 'FLORIANOPOLIS', 4205407, 48);

INSERT INTO MC_CIDADE (CD_CIDADE, SG_ESTADO, NM_CIDADE, CD_IBGE, NR_DDD)
    VALUES (SQ_MC_CIDADE.NEXTVAL, 'SC', 'BALNEARIO CAMBORIU', 4202008, 48);


/*UPDATE MC_CIDADE
SET CD_CIDADE = 12, SG_ESTADO = 'RN', NM_CIDADE = 'PARNAMIRIM', CD_IBGE = 2403251,NR_DDD = 84
WHERE CD_CIDADE = 12 */
 
COMMIT;

/* c) Parte 3: Para cada cidade, associe no minimo 1 bairro e para cada bairro, associe 
2 enderecos. Utilize nomes significativos e coerentes, de acordo com a base 
do Correio*/ 

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 1, 'JARDIM SAO JOSE', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 1, 'PARQUE SAO QUIRINO', 'ZONA NORTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 2, 'VISTA VERDE', 'ZONA NORTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 2, 'JARDIM COLONIAL', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 3, 'PLANALTO VERDE', 'ZONA OESTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 3, 'NOVA ALIANCA', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 4, 'ALVORADA', 'ZONA LESTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 4, 'TOCANTINS', 'ZONA OESTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 5, 'PAMPULHA', 'ZONA NORTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 5, 'DISTRITO INDUSTRIAL DO JATOBA', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 6,'SANTA LUZIA', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 6,'ENCOSTA DO SOL', 'ZONA OESTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 7,'KENNEDY', 'ZONA OESTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 7,'MAURICIO DE NASSAU', 'CENTRO');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 8,'PINA', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 8,'BAIRRO DO RECIFE', 'CENTRO');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 9,'DOM AVELAR', 'ZONA NORTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 9,'SAO GONCALO', 'ZONA OESTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 10,'PONTA NEGRA', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 10,'TIROL', 'CENTRO');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 11,'ALTO SUMARE', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 11,'RINCAO', 'ZONA LESTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 12,'CENTRO', 'ZONA CENTRAL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 12,'NOVA PARNAMIRIM', 'ZONA LESTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 13,'PARQUE GUARANI', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 13,'AVENTUREIRO', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 14,'PRAIA BRAVA','ZONA NORTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 14,'CAMPECHE','ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 15,'BARRA', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
    VALUES (SQ_MC_BAIRRO.NEXTVAL, 15,'PIONEIROS', 'ZONA NORTE');

COMMIT;

-- c) parte 4: PARA CADA BAIRRO , ASSOCIE 2 ENDERECOS. 

INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 1 , 'RUA RODOLFO PANONI' , 13051170)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 1 , 'RUA MIGUEL JOAO JORGE' , 13051172)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 2 , 'RUA LUIS PAOLIERI' , 13088390)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 2 , 'RUA CYRENIA ARRUDA CAMARGO' , 13088106)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 3 , 'RUA ARUBA' , 12223780)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 3 , 'RUA BAVIERA' , 12223760)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 4 , 'RUA CELINA' , 12234360)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 4 , 'RUA BALTAZAR' , 12234360)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 5 , 'RUA ALEXANDRE SETI' , 14056604)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 5 , 'RUA JOAQUIM LEONARDO' , 14056603)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 6 , 'RUA JOSE JAIME DELIBO' , 14026563)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 6 , 'RUA PEDRO GIROTO' , 14026560)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 7 , 'RUA JOAO AUGUSTO LOPES' , 38407072)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 7 , 'RUA MARIA AUGUSTA MORAIS' , 38407069)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 8 , 'RUA AGENOR BORGES' , 38415321)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 8 , 'RUA JOAQUIM CARRIJO NETTO' , 38415360)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 9 , 'RUA LIDER' , 31270480)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 9 , 'RUA PROF. NELSON DE SENA' , 31270383)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 10 , 'RUA VALE DO IPE' , 30666470)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 10 , 'RUA ZUMBI DOS PALMARES' , 30666475)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 11 , 'RUA IBITIGUAIA' , 36031000)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 11 , 'RUA HUMBERTO BERZOINI' , 36031060)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 12 , 'RUA ENG. REGINALDO ARCURI' , 36083018)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 12 , 'RUA POETA DALTEMAR LIMA' , 36083015)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 13 , 'RUA CADENTE' , 55780000)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 13 , 'RUA MERCURIO' , 55040260)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 14 , 'AVENIDA OSWALDO CRUZ' , 55012040)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 14 , 'RUA TEOFILO DIAS' , 55012710)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 15 , 'RUA TOME GIBSON' , 51011480)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 15 , 'RUA AMAZONAS' , 51011020)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 16 , 'RUA DO BOM JESUS' , 50030170)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 16 , 'RUA MADRE DE DEUS' , 50030230)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 17 , 'RUA DA AMIZADE' , 56323130)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 17 , 'AVENIDA DA ESPERANCA' , 56323140)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 18 , 'RUA VINTE E OITO' , 56312281)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 18 , 'RUA SILVESTRE DIAS PINHEIRO' , 56312285)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 19 , 'RUA ERIVAN FRANCA' , 59090100)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 19 , 'RUA PEDRO FONSECA FILHO' , 59090080)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 20 , 'RUA CEARA MIRIM' , 59020240)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 20 , 'RUA JOSE MARTINS BEZERRA' , 59020215)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 21 , 'RUA SABIA' , 59632140)
      
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 21 , 'RUA ZEUS' , 59632215)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 22 , 'RUA ANTONIO JOSE DE LIMA' , 59630508)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 22 , 'RUA SERGINA LUCINDA ALVES' , 59630640)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 23 , 'RUA EDGAR DANTAS' , 59140290)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 23 , 'RUA TENENTE OSORIO' , 59140285)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 24 , 'RUA DAS AMORAS' , 59152675)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 24 , 'RUA SERRA DO CARMO' , 59152698)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 25 , 'RUA LOURIVAL LEITE PALHARES' , 89209550)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 25 , 'RUA HERMINIO PICOLLI' , 89209615)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 26 , 'RUA UIRAPURU' , 89225680)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 26 , 'RUA ARARA' , 89226010)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 27 , 'RUA CARLOS DA COSTA PEREIRA' , 88056810)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 27 , 'RUA NICOLINO TANCREDO' , 88056840)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 28 , 'RUA DAS CORTICEIRAS' , 88063160)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 28 , 'RUA JARDIM DOS EUCALIPTOS' , 88063270)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 29 , 'RUA PEDRO PINTO CORREA' , 88332240)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 29 , 'RUA BENTO CUNHA' , 88332170)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 30 , 'RUA ROMEU PEREIRA' , 88331045)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 30 , 'RUA MIGUEL MATTE' , 88331030)
    
COMMIT;

/*d) Por fim, cadastre na tabela de ENDERECO FUNCIONARIO todos os funcionarios com no minimo 1 endereco para cada um. 
Escolha varios estados do Brasil, ou seja, um funcionario pode residir em mais de uma localidade, dado que a empresa 
Melhores Compras incentiva o trabalho em formato home office. 
*/

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (1 , 60 , 376 , 'CASA' , TO_DATE('10/10/2000','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (2 , 59 , 23 , 'CASA' , TO_DATE('18/07/2008','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (3 , 58 , 549 , 'CASA' , TO_DATE('31/03/2009','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (4 , 57 , 214 , 'CASA' , TO_DATE('31/03/1990','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (5 , 56 , 800 , 'APARTAMENTO 10' , TO_DATE('31/08/2011','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (6 , 55 , 466 , 'CASA 2' , TO_DATE('21/07/2010','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (7 , 54 , 322 , 'EM FRENTE A PIZZARIA ROMANA' , TO_DATE('14/06/2011','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (8 , 53 , 2 , 'APARTAMENTO 70' , TO_DATE('18/05/1991','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (9 , 52 , 485 , 'APARTAMENTO A BLOCO B' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (10 , 51 , 100 , 'APARTAMENTO 100' , TO_DATE('23/09/2009','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (11 , 50 , 12 , 'APARTAMENTO A BLOCO C' , TO_DATE('20/11/2006','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (12 , 49 , 52 , 'CASA SEGUNDO ANDAR' , TO_DATE('20/11/1992','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (13 , 48 , 51 , 'CASA' , TO_DATE('10/02/1997','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (14 , 47 , 54 , 'CASA' , TO_DATE('17/06/2006','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (15 , 46 , 1999 , 'CASA' , TO_DATE('18/09/2012','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (16 , 45 , 42 , 'CASA' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (17 , 44 , 367 , 'CASA' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (18 , 43 , 409 , 'CASA' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (19 , 42 , 399 , 'CASA' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (20 , 41 , 121 , 'CASA' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (21 , 4 , 13 , 'CASA' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (22 , 39 , 378 , 'BLOCO A CASA 10' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (23 , 38 , 2030 , NULL , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (24 , 37 , 153 , NULL , TO_DATE('15/02/2008','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (25 , 36 , 132 , NULL , TO_DATE('15/02/2023','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (26 , 35 , 75 , NULL , TO_DATE('15/02/2023','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (27 , 34 , 650 , 'AP 2062' , TO_DATE('15/02/2023','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (28 , 33 , 30 , NULL , TO_DATE('15/02/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (29 , 32 , 171 , NULL , TO_DATE('15/02/2023','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (30 , 31 , 14 , NULL , TO_DATE('15/02/2023','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (31 , 30 , 171 , NULL , TO_DATE('18/02/2021','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (32 , 29 , 32 , NULL , TO_DATE('15/02/2010','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (33 , 28 , 27 , 'BLOCO A CASA 20' , TO_DATE('02/11/2018','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (34 , 27 , 275 , NULL , TO_DATE('02/07/2017','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (35 , 26 , 12 , 'APTO 1806' , TO_DATE('15/02/2014','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (36 , 25 , 16 , NULL , TO_DATE('16/02/2009','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (37 , 24 , 2 , NULL , TO_DATE('25/02/2009','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (38 , 23 , 96 , NULL , TO_DATE('21/06/2012','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (39 , 22 , 242 , 'CASA' , TO_DATE('25/02/2009','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (40 , 21 , 781 , 'CASA' , TO_DATE('09/04/2010','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (41 , 20 , 33 , 'CASA' , TO_DATE('07/03/2010','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (42 , 19 , 222 , 'CASA' , TO_DATE('08/09/2015','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (43 , 18 , 88 , 'CASA' , TO_DATE('09/08/2018','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (44 , 17 , 22 , 'CASA' , TO_DATE('01/02/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (45 , 16 , 253 , 'CASA' , TO_DATE('09/08/2022','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (46 , 15 , 303 , NULL , TO_DATE('01/02/2000','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (47 , 14 , 82 , NULL , TO_DATE('01/02/2000','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (48 , 13 , 212 , NULL , TO_DATE('01/02/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (49 , 12 , 2 , NULL , TO_DATE('01/02/2006','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (50 , 11 , 90 , NULL , TO_DATE('02/01/2006','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (51 , 10 , 251 , NULL , TO_DATE('02/01/2006','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (1 , 9 , 160 , NULL , TO_DATE('10/10/2000','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (2 , 8 , 245 , NULL , TO_DATE('18/07/2008','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (3 , 7 , 223 , NULL , TO_DATE('31/03/2009','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (4 , 6 , 333 , NULL , TO_DATE('31/03/1990','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (5 , 5 , 74 , NULL , TO_DATE('31/08/2011','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (6 , 4 , 1211 , 'CASA' , TO_DATE('21/07/2010','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (7 , 3 , 112 , 'CASA' , TO_DATE('14/06/2011','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (8 , 2 , 129 , 'CASA' , TO_DATE('18/05/1991','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (9 , 1 , 249 , NULL , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

COMMIT;

--e)Cadastre no mínimo 10 CLIENTES PESSOAS FÍSICAS e 5 CLIENTES PESSOA JÚRIDICA e associe no mínimo 1 endereço para cada cliente. 
--Utilize nomes significativos e relevantes
INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL ,  'Junior da Silva' , 1 , 150 , 'A' , 'j_dasilva@outlook.com' , 19988579990  , 'jsilva' , 'js90*');

INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'Beatriz Almeida' , 2 , 2500 , 'A' , 'bia.almeida@yahoo.com.br' , 84981523321 , 'bia.almeida82' , 'BAlmeida82#');

INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'Carlos da Costa' , 3 , 4000 , 'A' , 'cccosta@fiap.com.br' , 16996465678 , 'ccosta' , 'azulblue123');

INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'Renata Oliveira ' , 2 , 2000 , 'A' , 'r_oliveira@gmail.com' , 32991998076 , 'R.oliveira' , 'oliveira.R321');

INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'Juliana Alcantara Moreira' , 5 , 11000 , 'A' , 'ju.moreira@gmail.com' , 34999815646 , 'ju.moreira79' , '*moreira79');

INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'Carla Cristina Rodrigues ' , 4 , 5500 , 'A' , 'carla_rodrigues@outlook.com' , 16999916754 , 'carla.crodrigues' , 'CCR2000');

INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'Simone Paulino' , 1 , 320 , 'A' , 'spaulino@yahoo.com.br' , 47991998979 , 'simone.PAULINO' , 'SM7719');

INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'Andreia Meira' , 1 , 280 , 'A' , 'meira.andreia@fiap.com.br' , 84981568801 , 'Ameira' , 'Ameira22');

INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'Ana Fraki' , 5 , 14500 , 'A' , 'aninha_fraki@yahoo.com.br' , 47998985754 , 'ANAfraki' , 'Fraki3434');

INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'Cleber Ferreira' , 4 , 6800 , 'A' , 'cleber.fer@outlook.com' , 32999917856 , 'FCleber' , 'FCleber84');

INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'Martex Correias E Mangueiras Ltda' , 5 , 45000 , 'A' , 'atendimento@lojamartex.com.br' , 3233438949 , 'LMartex' , 'MartexLoja2002');

INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'Movelar Moveis Ltda' , 5 , 38000 , 'A' , 'atendimento@movelar.com.br' , 8133723919 , 'MovelarMoveis' , 'MM#4321');

INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'Submarino Comercial Ltda' , 5 , 90000 , 'A' , 'atendimento@submarino.com.br' , 1632724562 , 'subMAR' , 'ssMMcat');

INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'Cofesa Comercial Ferreira Santos Ltda' , 5 , 88000 , 'A' , 'atendimentosac@cofesacomercial.com.br' , 1632729900 , 'COFESA.comercial' , 'CCFS99');

INSERT INTO MC_CLIENTE (NR_CLIENTE ,  NM_CLIENTE ,  QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN , DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'Veja Calcados E Confeccoes Ltda' , 4 , 8800 , 'A' , 'sac@lojaveja.com.br' , 3433734809 , 'VEJA.loja' , 'VEja2001');

--Inserindo dados Clientes Pessoa Fisica
INSERT INTO MC_CLI_FISICA (NR_CLIENTE ,  DT_NASCIMENTO ,  FL_SEXO_BIOLOGICO ,  DS_GENERO ,  NR_CPF)
    VALUES (1 ,  TO_DATE('25/07/1990' , 'DD/MM/YYYY') , 'M' , 'MASCULINO' , 38460381800);

INSERT INTO MC_CLI_FISICA (NR_CLIENTE ,  DT_NASCIMENTO ,  FL_SEXO_BIOLOGICO ,  DS_GENERO ,  NR_CPF)
    VALUES (2 ,  TO_DATE('08/02/1982' , 'DD/MM/YYYY') , 'F' , 'FEMININO ' , 65787611906);

INSERT INTO MC_CLI_FISICA (NR_CLIENTE ,  DT_NASCIMENTO ,  FL_SEXO_BIOLOGICO ,  DS_GENERO ,  NR_CPF)
    VALUES (3 ,  TO_DATE('26/05/1980' , 'DD/MM/YYYY') , 'M' , 'MASCULINO' , 43564351523);

INSERT INTO MC_CLI_FISICA (NR_CLIENTE ,  DT_NASCIMENTO ,  FL_SEXO_BIOLOGICO ,  DS_GENERO ,  NR_CPF)
    VALUES (4 ,  TO_DATE('01/02/1986' , 'DD/MM/YYYY') , 'F' , 'FEMININO ' , 89734572103);

INSERT INTO MC_CLI_FISICA (NR_CLIENTE ,  DT_NASCIMENTO ,  FL_SEXO_BIOLOGICO ,  DS_GENERO ,  NR_CPF)
    VALUES (5 ,  TO_DATE('09/09/1979' , 'DD/MM/YYYY') , 'F' , 'FEMININO ' , 23495481802);

INSERT INTO MC_CLI_FISICA (NR_CLIENTE ,  DT_NASCIMENTO ,  FL_SEXO_BIOLOGICO ,  DS_GENERO ,  NR_CPF)
    VALUES (6 ,  TO_DATE('09/05/1995' , 'DD/MM/YYYY') , 'F' , 'FEMININO ' , 25780182845);

INSERT INTO MC_CLI_FISICA (NR_CLIENTE ,  DT_NASCIMENTO ,  FL_SEXO_BIOLOGICO ,  DS_GENERO ,  NR_CPF)
    VALUES (7 ,  TO_DATE('01/01/1977' , 'DD/MM/YYYY') , 'F' , 'FEMININO ' , 85951423141);

INSERT INTO MC_CLI_FISICA (NR_CLIENTE ,  DT_NASCIMENTO ,  FL_SEXO_BIOLOGICO ,  DS_GENERO ,  NR_CPF)
    VALUES (8 ,  TO_DATE('07/07/1995' , 'DD/MM/YYYY') , 'F' , 'FEMININO ' , 94712309587);

INSERT INTO MC_CLI_FISICA (NR_CLIENTE ,  DT_NASCIMENTO ,  FL_SEXO_BIOLOGICO ,  DS_GENERO ,  NR_CPF)
    VALUES (9 ,  TO_DATE('09/07/1980' , 'DD/MM/YYYY') , 'F' , 'FEMININO ' , 98724671276);

INSERT INTO MC_CLI_FISICA (NR_CLIENTE ,  DT_NASCIMENTO ,  FL_SEXO_BIOLOGICO ,  DS_GENERO ,  NR_CPF)
    VALUES (10 ,  TO_DATE('19/10/1984' , 'DD/MM/YYYY') , 'M' , 'MASCULINO' , 38762591878);

--Inserindo dados Clientes Pessoa Juridica
INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE ,  DT_FUNDACAO ,  NR_CNPJ , NR_INSCR_EST)
    VALUES (11 ,  TO_DATE('11/06/2002' , 'DD/MM/YYYY') , 50922610001 , 140347252114);

INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE ,  DT_FUNDACAO ,  NR_CNPJ , NR_INSCR_EST)
    VALUES (12 ,  TO_DATE('24/10/2012' , 'DD/MM/YYYY') , 12322610001 , 570317292124);

INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE ,  DT_FUNDACAO ,  NR_CNPJ , NR_INSCR_EST)
    VALUES (13 ,  TO_DATE('22/12/2000' , 'DD/MM/YYYY') , 22325970001 , 430327192424);

INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE ,  DT_FUNDACAO ,  NR_CNPJ , NR_INSCR_EST)
    VALUES (14 ,  TO_DATE('29/10/2004' , 'DD/MM/YYYY') , 44323270001 , 533311292134);

INSERT INTO MC_CLI_JURIDICA (NR_CLIENTE ,  DT_FUNDACAO ,  NR_CNPJ , NR_INSCR_EST)
    VALUES (15 ,  TO_DATE('06/09/1999' , 'DD/MM/YYYY') , 86923610001 , 420317192324);

COMMIT;

--Inserindo endereço do cliente
INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (1 , 2 , 442 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (2 , 45 , 38 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (3 , 11 , 67 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (4 , 24 , 898 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (5 , 16 , 24 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (6 , 9 , 78 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (7 , 60 , 97 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (8 , 44 , 289 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (9 , 51 , 384 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (10 , 22 , 32 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (11 , 32 , 1101 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (12 , 30 , 874 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (13 , 12 , 561 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (14 , 9 , 345 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

INSERT INTO MC_END_CLI (NR_CLIENTE, CD_LOGRADOURO_CLI, NR_END,DT_INICIO,ST_END)
    VALUES (15 , 13 , 89 , TO_DATE('14/04/2023' , 'DD/MM/YYYY') , 'A' );

COMMIT;

--f) Cadastre um novo cliente que já tenha um mesmo login já criado. (*Exiba a instrução SQL executada para realizar a 
--tarefa e apresente o resultado dessa execução). Foi possível incluir esse novo cliente? Explique?

INSERT INTO MC_CLIENTE (NR_CLIENTE , NM_CLIENTE , QT_ESTRELAS , VL_MEDIO_COMPRA , ST_CLIENTE , DS_EMAIL , NR_TELEFONE , NM_LOGIN,DS_SENHA)
    VALUES (SQ_MC_CLIENTE.NEXTVAL , 'MVP2L.SA' , 5 , 1000800 , 'A' , 'sac@mvp2l.com' , 84998789999 , 'VEJA.loja' , 'VEja2001');
/* Não foi possivel cadastrar um novo cliente, gerou a seguinte mesnagem de erro:
    
    "ORA-00001: restrição exclusiva (RM99237.UK_MC_CLIENTE_MM_LOGIN) violada"

Acontece este erro por conta da coluna estar com uma Unique Constraint. Sendo assim o conteudo desta coluna não pode repetir 
em nenhuma linha. 

*/

--g) Cadastre as seguintes categorias para os produtos: Artesanato; Áudio; Brinquedos; Celular e Smartphone; Colchões; 
--Esporte e Lazer; Ferramentas; Games; Informática; Livros; Pet Shop; TV e Utilidades Domésticas.

--Inserindo Categoria Artesanato
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Produtos de Artesanato sao as pecas feitas manualmente por um artesao', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'A'); 
--Inserindo Categoria Audio
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Produtos de audio estao relacionado com a t�cnica de gravacao, transmissao e reprodu��o dos sons', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'A');
--Inserindo Categoria Brinquedos
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'e considerado brinquedo todo e qualquer objeto utilizado para o divertimento de adultos e crian�as', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'A');
--Inserindo Categoria Celulares e Smartphones
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Todos os  celulares ou smartphones', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'A');
--Inserindo Categoria Colch�es
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Colchoes de todos os modelos', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'A');
--Inserindo Categoria Esporte e Lazer
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Todos os esportes livres para proporcionar lazer e diversao', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'A');
--Inserindo Categoria Ferramentas
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Todos os modelos de Ferramentas para auxiliar na realizacao de tarefas ', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'A');
--Inserindo Categoria Games
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Tudo de jogo ou videogame', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'A');
--Inserindo Categoria Livros
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Livros de todos os generos', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'A');
--Inserindo Categoria Pet Shop
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Tudo relacionado a Pet Shop', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'A');
--Inserindo Categoria TV
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Televisores de todos os modelos', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'A');
--Inserindo Categoria Utilidade Domesticas
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'P', 'Objetos uteis que sao utilizados no lar', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'I');

--h) Cadastre as seguintes categorias para os vídeos: Instalação do produto; Uso no cotidiano; Comercial com personalidade; entre outros.
-- Adicionando Categorias Instalacao do produto
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Como sera feita a instalacao do produto', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'A');
-- Adicionando Categorias Uso no cotidiano
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Como sera utilizado o produto no cotidiano', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'A');
-- Adicionando Categorias Comercial com personalidade
INSERT INTO MC_CATEGORIA_PROD (cd_categoria, tp_categoria, ds_categoria, dt_inicio, st_categoria)
    VALUES (SQ_MC_CATEGORIA.NEXTVAL, 'V', 'Comercial com personalidade', TO_DATE('10/04/2023', 'DD/MM/YYYY'),'A');

COMMIT;

--i) Cadastre 20 produtos e associe as categorias adequadas ao produto.
--Inserindo produtos da categoria Artesanato(1)
INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 1 , 'Tinta para Tecido Branco 37ml Acrilex' , 4.49 , 'Tinta para Tecido Branco 37ml Acrilex
    Tinta para Tecido Fosca Acrilex
    Embalagem: 37ml
    Cor: Cod. 519 Branco
    - Para ser utilizada em tecidos de algodao.
    - Nao utilizar em tecidos sinteticos ou engomados
    - Super resistencia a lavagens
    - Excelente cobertura com fixacao a frio
    - Pronta para uso, cores misciveis entre si
    Para diluicao, utilize o Diluente para Tinta Tecidos,  indicado para diluir,  retardar a secagem,  fazer tecnicas de matizados e sombreados,  mantendo a resistencia a lavagens.
    Modo de Usar:
    Pode ser aplicada com pincel,  esponja ou carimbo,  em tecidos de algodao sem goma (nao sinteticos).
    Lavar o tecido antes da pintura,  para retirar os residuos de goma.
    Apos a pintura, aguarde 72 horas para lavagem.');

INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 1 , 'Pincel chato numero 2 ref. 115-2 condor' , 4.37 , 'Pincel chato numero 2 ref. 115-2 condor
    PINCEL CHATO NUMERO 2 REF. 115-2 CONDOR');

-- Inserindo produtos da categoria Audio(2)
INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 2 , 'Caixa De Som Bluetooth 5.0 Monitor Edifier R1080bt 24w Home audio Multimidia' , 791.97 , 'Caixa De Som Bluetooth 5.0 Monitor Edifier R1080bt 24w Home audio Multimidia Speaker
    MONITOR DE aUDIO 24W RMS - Bivolt
    MARCA: EDIFIER
    MODELO: R1080BT
    QTDE: 1 PAR - Duas Caixais uma Ativa/Passiva
    - INDICADO PARA HOME STUDIO 100%
    - Delicado e simples com design elegante.
    - Estrutura de madeira MDF , 
    - Bluetooth 5.0 ,  desempenho mais estavel ,  maior distancia de transmissao
    - Duas entradas para conexao simultanea
    Estrutura simples e detalhe charmoso
    Com design estilo nordico minimalista ,  linhas simples ,  clean e elegante ,  a R1080BT EDIFIER torna o ambiente de audio com mais elegancia alem da definicao de audio.
    Acustica
    Estrutura de madeira construida em MDF e mais estavel e pode reduzir efetivamente a interferencia de ressonancia ,  para reproduzir um som mais natural e puro.
    Operacao simples e direta.
    Com apenas 3 botoes ,  a usabilidade da caixa de som multimidia R1080BT EDIFIER e bem simples e sofisticada.
    No botao de liga/desliga e possivel alternar entre as entradas de audio. Os botoes de aumentar e diminuir o volume tambem estao posicionados na parte superior para uma acessibilidade mais rapida e pratica.
    Revestimento Especial
    Um revestimento especial na ""bola de seda"" do tweeter de 19mm faz o desempenho do som mais claro e delicado.
    Midwoofer 4"" Baixa Distorcao
    O diafragma ondulado reduz a vibracao da secao transversal com menor distorcao e revela totalmente os detalhes de frequencias graves e medias.
    Ambientes Internos
    Um ambiente de ate 30m2 e totalmente preenchido com os 24wRMS.
    e mais que suficiente para desfrutar de um som com qualidade superior EDIFIER.
    Uma porta bass reflex permite que o ar circule mais livremente ,  melhorando sua eficiencia. Isso significa que voce obtem uma frequencia de corte mais baixa no filtro passa-baixo ,  o que melhora bastante a resposta sonora; Alem disso ,  voce obtem distorcao reduzida porque a porta esta fazendo o seu trabalho perfeitamente ,  o que reduz a quantidade de ressonancia do gabinete.
    DADOS TeCNICOS
    - Potencia: 12W + 12W
    - Entrada de audio: AUX ,  LINE IN ,  Bluetooth
    - Forma de ajuste: botao de ajuste
    - Distorcao harmônica total da pressao do som: = 7%
    - Resposta de frequencia: 67Hz-20kHz
    - Sensibilidade de entrada:
    - 700  50mV (PC);
    - 550  50mV (AUX);
    - 550  50mFFs (Bluetooth)
    - Relacao sinal / ruido dB (A): 85dB (A)
    - Nivel de ruido: =25dB (A)
    - Compatibilidade: Bluetooth ,  P2
    - Alimentacao: Bivolt
    ITENS INCLUSOS
    1 Par de caixas de som multimidia R1080BT EDIFIER (01 ativo + 01 passivo)
    1 Cabo de audio AUX P2
    1 Manual do usuario
    Garantia de 12 meses.');

INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 2 , 'Mini Amplificador Som Audio Bluetooth Usb Mp3 Fm Karaoke - Lelong' , 241.45 , 'Mini Amplificador Som Audio Bluetooth Usb Mp3 Fm Karaoke
    Amplificador feito para quem gosta de um som com extrema qualidade ,  e ainda voce pode conseguir atingir um nivel sonoro limpo e muito pratico ,  voce conta com todas as outras funcionalidades que acompanha o produto Amplificador lelong 704 serve para karaoke Bluetooth Mp3 Bivolt 2 saidas de 60 rms cada  ,  total 120 rmsFonte de alimentacao 12 voltsSnr -80dbn Com controle');

-- Inserindo produtos da categoria Brinquedos(3)
INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 3 , 'Cactos Dancante Falante ,  Toca Danca Fala e Pisca - RB Colecoes' , 52.37 , 'Cactos Dancante Falante ,  Toca Danca Fala e Pisca. O Cacto dancante tem mais de 100 musicas ,  repete a fala ,  danca ,  pisca a luz');

INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 3 , 'Brinquedo Lanca Bolha de Sabao Diversao Tubarao - Art Brink' , 22.37 , 'Brinquedo Lanca Bolha de Sabao Diversao Tubarao
    Trazemos aqui a diversao classica mas com nova cara ,  fazer bolhas de sabao agora e muito mais divertido!
    Com o Lanca Bolhas de Sabao Basta apertar o gatilho que a diversao esta garantida!
    Contem 01 lancadpr de bolhas; 01 ponteira do lancador e 01 refil de 55mL com Liquido
    +3 anos
    Modo de Usar:
    1) Abra a Tampa do Frasco e retire o Lacre
    2) Despeje um pouco da solucao na tampa , 
    3) Mergulhe o bico na solucao e .... APERTE o Gatilho
    BENEFiCIOS: Auxilia na interacao da crianca ,  promove distracao ,  diversao e nao gasta energia!');

-- Inserindo produtos da categoria Celulares e Smartfones(4)
INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, DS_PRODUTO, VL_UNITARIO, DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL,4,'Apple iPhone 14 Plus 128GB Estelar 6,7? 12MP',6209.1,'Com o iPhone 14 Plus, voce pensa grande na supertelona de 6,7 polegadas* e tem bateria para o dia todo**. Usa o novo sistema de camera dupla para fazer fotos espetaculares em ambientes com pouca ou muita luz. E ganha tranquilidade com a Deteccao de Acidente***, um novo recurso de seguranca que liga para a emergencia se voce nao puder. Avisos legais *A tela tem bordas arredondadas. Quando medida como um retangulo, a tela tem 6,68 polegadas na diagonal. A area real de visualizacao e menor. **A duracao da bateria varia de acordo com o uso e a configuracao. Consulte apple.com/br/batteries para obter mais informacoes. ***O SOS de Emergencia usa uma conexao de rede celular ou chamadas Wi-Fi. ****e preciso ter um plano de dados. 5G so esta disponivel em alguns paises e por meio de determinadas operadoras. As velocidades variam de acordo com as condicoes e operadoras locais. Para obter detalhes sobre a compatibilidade com 5G, entre em contato com sua operadora e consulte apple.com/br/iphone/cellular. *****O iPhone 14 Plus e resistente a respingos, agua e poeira e foi testado em condicoes controladas em laboratorio, classificado como IP68 segundo a norma IEC 60529 (profundidade maxima de seis metros por ate 30 minutos). A resistencia a respingos, agua e poeira nao e uma condicao permanente e pode diminuir com o tempo. Nao tente recarregar um iPhone molhado. Veja instrucoes de limpeza e secagem no Manual do Usuario. Danos decorrentes de contato com liquidos nao estao incluidos na garantia. ******Alguns recursos podem nao estar disponiveis em todos os paises ou regioes.');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, DS_PRODUTO, VL_UNITARIO, DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL,4,'Smartphone Samsung Galaxy S23 256GB Verde 5G 8GB RAM 6,1" Cam Tripla',5849,'Smartphone Samsung Galaxy S23 256GB Violeta 5G 8GB RAM 6,1" Cam Tripla + Selfie 12MP
Para voce que esta a procura de um novo smartphone e dar aquele upgrade no seu dia a dia no trabalho ou para navegar nas redes sociais, precisa conhecer o Samsung Galaxy S23 na cor violeta. e o smartphone top de linha pra quem quer um aparelho completo pra jogos, estudos e trabalho. Ele possui 256GB de armazenamento interno para guardar diversos aplicativos, fotos, videos e jogos, 8GB de memoria RAM e processador Qualcomm Snapdragon 8 Gen 2 que evita aquelas travadas durante o uso. A tela dele e Dynamic AMOLED 2X de 6,1"" com resolucao FHD+ (1080x2340), a camera traseira e tripla de 50MP +12MP + 10MP com Zoom Digital ate 30x e optico 3x , perfeita para tirar muitas fotos e a frontal de 12MP faz selfies que ficam otimas para postar nas redes sociais. E ainda, e Dual Chip com tecnologia 5G, oferece leitor de impressao digital, reconhecimento Facial e protecao IP68 que torna o aparelho resistente a agua, mesmo se ele for submerso por 30 minutos a 1,5 metro de profundidade. Atencao: Produto nao acompanha fone de ouvido.');

-- Inserindo produtos da categoria Colchoes(5)
INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 5 , 'Colchao Solteiro Molas Ensacadas Bamboo BF Colchoes 88x188x21cm' , 719.91 , 'Colchao Solteiro Molas Ensacadas Bamboo BF Colchoes 88x188x21cm
    Bf Bamboo e ideal para quem busca conforto ,  aconchego e bem estar ao se deitar.
    Com seu inovador sistema de molas ensacadas e costuradas individualmente ,  proporciona uma adaptacao ao formato do corpo. Este e ideal para casais de pesos diferentes ,  pois os movimentos de um nao sao transmitidos ao parceiro do outro lado.
    As laterais sao em tecido Jacquard Italiano ,  que oferece alem de um lindo acabamento maior resistencia e durabilidade ao colchao. Seu tampo em tecido com fibras naturais de bamboo oferecem uma sensacao termica mais agradavel ,  alem de um excelente bactericida natural ,  minimizando reacoes alergicas durante seu sono.
    Tipo de conforto: Intermediario
    Caracteristicas Internas e Beneficios:
    - Molas ensacadas individualmente: Possibilita que o movimento feito em um lado do colchao nao seja sentido em outro ,  proporcionando individualidade entre os movimentos do casal.
    - Espuma A.G 80 garantindo firmeza e durabilidade ao colchao.
    - Espuma Densidade 23 garantindo conforto maior.
    - Poly board: Oferece maior resistencia e firmeza as laterais do colchao ,  proporcionando uma maior durabilidade.
    Tecido Superior:
    Poliester com viscose de bambu ,  bordado com fibra de poliester com tratamento antimicrobiano ,  segundo analises laboratoriais da Controlbio ,  o agente elimina 99 , 99% das bacterias que entram em contato com a fibra.
    Cor: Bege
    Tecido Lateral:
    Jacquard
    Cor: Marrom
    Tecido Inferior:
    Antiderrapante.
    Tamanho:
    Solteiro - 88 x 188 x 21 cm
    Suporte de Peso ate 100Kg por pessoa.
    Garantia: 01 Ano
    Garantia do box: 03 Meses ( 90 dias)
    Atencao a entrega:
    Nao fazemos entregas em locais de acesso apenas por estrada de terra ,  estrada de areia ,  por balsa ou barco. Nao subimos produtos por escadas e elevadores.
    Nao nos responsabilizamos por montagens ,  desmontagens e instalacoes. Confira as dimensoes do produto no momento da compra e certifique-se que o item passara normalmente por elevadores ,  portas ,  escadas e/ou corredores ,  evitando assim futuros desagrados
    Selo Inmetro: 004175/2017');

INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 5 , 'Colchao Casal Ortopedico Sleep Extra Firme 138x188x17cm - BF Colchoes' , 539.91 , 'Informacoes do Produto
    Colchao Casal Ortopedico Sleep Extra Firme 138x188x17cm - BF Colchoes
    O Ortopedico Sleep da BF Colchoes e ideal para quem busca um colchao com estrutura mais firme ,  pois promove a sustentacao ideal para a coluna.
    O colchao e um dos elementos fundamentais em nosso cotidiano ,  portanto precisa ser um forte aliado a nossa saude.
    Contem:
    01 Colchao Casal Ortopedico
    Caracteristicas Internas e Beneficios do Colchao:
    EPS - Centro em poliestireno expandido ,  que garante firmeza e durabilidade ao colchao.
    Espuma de Densidade 28
    Tampo em Malha
    Tecido: 100% poliester com tratamento antimicrobiano. Segundo analises laboratoriais da Controlbio ,  o agente elimina 99 , 99% das bacterias que entram em contato com a fibra.
    Tamanho: Casal
    Largura: 138 cm
    Comprimento: 188 cm
    Altura: 17 cm
    Nivel de conforto: Extra Firme
    Suporte De Peso: Ate 120 kg por Pessoa
    Garantia: Colchao: 01 Ano
    Certificados de Qualidade dos Colchoes BF:
    Pro-Espuma e Pro-Molas
    INER - Instituto Nacional de Estudos do Repouso
    Qualidade ISO 9001
    Inmetro
    Selo Inmetro: 004175/2017 OCP: 0095
    Atencao a entrega:
    Nao fazemos entregas em locais de acesso apenas por estrada de terra ,  estrada de areia ,  por balsa ou barco. Nao subimos produtos por escadas e elevadores.
    Nao nos responsabilizamos por montagens ,  desmontagens e instalacoes. Confira as dimensoes do produto no momento da compra e certifique-se que o item passara normalmente por elevadores ,  portas ,  escadas e/ou corredores ,  evitando assim futuros desagrados.');

-- Inserindo produtos da categoria Esporte e Lazer(6)
INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 6 , 'Sapatilha Boxe Everlast Ultimate ELM-94H' , 213.89 , 'Sapatilha Boxe Everlast Ultimate ELM-94H
    Inspirada no DNA da Everlast ,  a linha Fight foi criada pensando no profissional de luta. Com produtos altamente tecnologicos ,  os modelos atendem os requisitos exigidos pelos esportes de combate ,  sao mais leves ,  flexiveis e estruturados.');

INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 6 , 'Bola de FutVolei IDEA Original Esporte Lazer Tamanho Oficial' , 71.9 , 'Bola de FutVolei IDEA Original Esporte Lazer Tamanho Oficial
    Tamanho Oficial
    Sintetico
    Costura a maquina
    Cor Sortida
    Costurada a maquina
    Peso: 280 g
    Para esportes e lazer com a familia e amigos!');

-- Inserindo produtos da categoria Ferramentas(7)
INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 7 , 'Chave ajustavel inglesa cromada 6 Pol NOVE54' , 25.25 , 'Peso de 146g ,  comprimento de 6 polegadas ,  abertura de 18.0 mm ,  material em aco carbonado e acabamento cromado fosco');

INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 7 , 'Chave Grifo 24 POL HEAVY DUTY Industrial MTX' , 62.49 , 'Peso de 456g ,  tamanho de 24 polegadas (600 mm) ,  modelo americano ,  mordentes em aco ,  cor vermelha e preto.');

-- Inserindo produtos da categoria Games(8)
INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 8 , 'God Of War Hits' , 56.05 , 'Classificacao indicativa: nao recomendado para menores de 18 anos. Tipo de midia Blu-Ray. Plataforma PS4. Compativel com controle dualshock 4.  1 jogador on line. Idioma do Manual em Portugues - BR. Espaco requerido no disco rigido no minimo de 50 GB. Saida de video  de 1080p. Conteudo da embalagem: 1 jogo. Dimensoes 19(a) x 3(l) x 13 , 50(c) cm. Legenda: PT-BR. Idioma: PT-BR. Fabricante do Software: Solutions 2 GO. Developer: Santa Monica Studio. Genero: Acao. Inadequacoes: violencia extrema e linguagem impropria. Garantia: 3 meses. Peso: 200g');

INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 8 , 'Minicraft Starter Collection' , 189.9 , 'Classificacao indicativa: Livre. Tipo de midia: Blu-Ray. Plataforma: Playstation 4. Compativel com controle dualshock 4. Numero de jogadores offline: 1 a 4 jogadores. Numero de jogadores online: 2 a 8 jogadores. Idioma do Manual: PT-BR. Espaco requerido no disco rigido: requer minimo de 11 GB. Saida de video: 1080p. Conteudo da embalagem: 1 jogo. Dimensoes: 19(a) x 13(l) x 3(c) cm. Legenda: PT-BR. Idioma: PT-BR. Fabricante do software: Solutions 2GO. Developer: MOJANG. Genero: Estrategia/Aventura. Inadequacoes: Nao ha inadequacoes. Garantia: 3 meses. Peso: 200g.');

-- Inserindo produtos da categoria Informatica(9)
INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 9 , 'Camera Web Logitech C505e HD 30 fps' , 195 , 'Marca: Logitech. Linha: HD. Modelo: C505e. Resolucao maxima de video: 1280 px x 720 px. Tipo de resolucao maxima de video: HD. Resolucao de imagem da camera: 1.2 Mpx. Interfaces: USB-A. Funcoes: Correcao de luz , Microfone com cancelamento de ruido , Microfone integrado , Panorama. Sistemas operacionais minimos requeridos: Chrome OS , Windows 8 , macOS 10.10. Quadros maximos por segundo: 30 FPS. Dispositivos recomendados: Desktop PC , Notebook. Acessorios incluidos: Clipe , Guia do usuario. Aplicacoes compativeis: Cisco Jabber , Google Meet y Voice , Microsoft Teams , Skype for Business , Zoom. angulo de visao: 60°. Comprimento do cabo: 2 m. Profundidade: 24.19 mm. Largura: 72.91 mm. Altura: 31.91 mm. Peso: 75 g.');

INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 9 , 'Monitor 23.8 Aoc Ips Full Hd Hdmi Vga Widescreen Usb 24p1u' , 1757.5 , 'Monitor 23 , 8"" LED Widescreen Full HD HDMI USB VGA 24p1u AOC Bivolt Caracteristicas: Full HD. Ajuste de Altura auto pivot. Marca: AOC. Voltagem: Bivolt. Referencia: 7898620270643. Cor: Preto. Compatibilidade: Windows ,  MAC ,  Linux. Tipo de painel: LED. Tamanho do painel: 23 , 8"" Widescreen. Tamanho da imagem visivel (diagonal): 60 , 4 cm. Pixel pitch: 0 , 274 mm. Contraste estatico: 1.000:1. Frequencia do painel: 60 Hz. Tratamento da tela: Anti-reflexivo. angulo de visao horizontal: 178. Contraste (Dinamico): 50.000.000:1. angulo de visao vertical: 178. Brilho: 250 cd/m2. Resolucao maxima: 1920 x 1080 @ 60 Hz (FULL HD). Tempo de resposta: 5 ms. Conexoes: VGA: 1 | Display Port: 1 | HDMI: 1 | USB: 4. Fonte: Interna - 100~240V - 50/60 Hz. Controles manuais: Ligar / desligar ,  Menu / Enter ,  Proporcao / Volume da imagem ,  Fonte / Auto / Sair ,  Visao clara. Dimensoes da Embalagem (AxLxP): 40cm x 75cm x 18cm. Peso Bruto (Kg): 7 , 3. Garantia: 36 Meses');

-- Inserindo produtos da categoria Livros(10)
INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 10 , 'Todo esse Tempo - Rachael Lippincott' , 26.36 , 'Marca: Alt. Editora: Alt. Editora: Alt. Referencia: 9786588131084. Titulo: Todo esse Tempo. Autor: Lippincott ,  Rachael ,  Daughtry ,  Mikki. Formato: Impresso. Edicao: 1ª.  Idioma: Portugues. Numero de paginas: 352. ISBN: 9786588131084. Peso do produto: 381g. Dimensoes do produto: Altura: 21cm Largura: 14cm Profundidade: 1 , 2cm. Prazo de garantia: 03 meses de garantia legal. Conteudo da embalagem: 1 Livro');

INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 10 , 'A Garota do Lago - Charlie Donlea' , 8.79 , 'Marca: Faro Editorial. Editora: Faro Editorial. Referencia: 9788562409882. Titulo: A garota do lago. Autor: Charlie Donlea. Formato: Impresso. Tipo: Livro brochura (paperback). Edicao: 1. Edicao. Classificacao: Ficcao ,  Ficcao Cientifica ,  Geral. Ano de publicacao: 2017. Idioma: Portugues. Numero de paginas: 296. ISBN: 978-85-62409-88-2. Peso do Produto: 525g. Dimensoes do Produto: Largura: 15cm ,  Altura: 23cm ,  Profundidade: 2 , 6cm. Prazo de Garantia: 3 Meses de garantia legal. Conteudo da Embalagem: 1 Livro.');

-- Inserindo produtos da categoria Pet Shop(11)
INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 11 , 'Gaiola para Porquinho-da-india Monaco unico' , 379.9 , 'Marca: Monaco.  Material de qualidade ,  com acabamento em Epoxi e pintura na cor branca ,  trazendo durabilidade. Medidas aproximadas: Altura: 48cm. Largura: 41cm. Comprimento: 61cm');

INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 11 , 'Gaiola com Escada Hamster Monaco Verde unico' , 264.9 , 'Marca: Monaco.  Caracteristicas: 2 andares. Com rodinha para exercicios. Ideal para diversao e movimentacao. Medidas aproximadas: Altura: 40 cm x Largura: 26 cm x Comprimento: 40 cm');

-- Inserindo produtos da categoria TV(12)
INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 12 , 'Smart TV 50"" Android 4K UHD LED - Philips' , 3449 , 'Referencia do modelo: 50pug-7406/78. Caracteristicas - resolucao da imagem: 3840x2160. Proporcao da imagem: 16:9. Tamanho da memoria (flash): 8 gb. Conteudo da embalagem: 01 smart tv ,  01 controle remoto ,  01 cabo de energia ,  01 suporte para cima da mesa ,  02 pilhas aaa ,  01 manual do produto ,  voltagem: 220v ,  fornecedor: philips. Dimensoes aproximadas do produto: altura: 64 , 73 cm (sem base)/ 67 , 8 cm (com base) ,  largura: 111 , 3 cm ,  comprimento: 8 , 72 cm (sem base)/ 24 , 8 cm (com base). Garantia do fornecedor: 1 ano contra defeitos de fabricacao');

INSERT INTO MC_PRODUTO (CD_PRODUTO, CD_CATEGORIA, DS_PRODUTO, VL_UNITARIO, DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL ,12,'Smart Tv 43"" Uhd 4K Samsung Crystal Led - Bivolt',2449.9,'Caracteristicas -  Smart TV. Sistema operacional: Tizen. . Processador: Crystal 4K.. Assistente de Voz : Bixby, Alexa e Google Assistant. Aplicativos Pre-instalados: Sim. Tamanho da tela: 43 polegadas. Resolucao: 3,840 x 2,160. Frequencia: 60 Hz. audio: Potencia (RMS): 20 W. Conectividade: Entrada HDMI : Sim (3). Entrada USB: Sim (2). Entrada Ethernet: Sim. Conexoes sem fio: Wifi 5 e Bluetooth BT 5.2. Outras conexoes: HDMI A / Return Ch. Support, Entrada de RF (terrestre/entrada de cabo), eArc e Anynet+ (HDMI-CEC). Especificacoes Tecnicas Marca: Samsung. Modelo: Smart Tv 43? UHD 4k. Dimensoes com Suporte (LxAxP): 96,5cm x 59,9cm x 20,5cm. Dimensoes sem Suporte: (LxAxP): 96,5cm x 55,9cm x 2,5cm. Tipo de Furacao: VESA. Peso aproximado do produto com suporte: 8,4Kg. Peso aproximado do produto sem suporte: 8,1Kg. Conteudo da Embalagem: 01 Smart TV; 01 Controle; Garantia Fornecedor: 1 Ano.');

-- Inserindo produtos da categoria Utilidades Domesticas(13)
INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 13 , 'Fervedor Tramontina em Aluminio com Revestimento Interno e Externo' , 69.9 , 'Corpo de aluminio com espessura de 1 , 4 mm que proporciona cozimento rapido e uniforme. Revestimento interno e externo de antiaderente Starflon Max que nao gruda ,  e facil de limpar ,  mais duravel e nao e prejudicial a saude ,  pois e livre de PFOA. Cabo de baquelite antitermico que oferece seguranca. Altura: 10.30 cm. Largura: 13.30 cm. Diametro: 12 , 00. Peso: 240g. Capacidade: 1 litro.');

INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 13 , 'Panela de Pressao Tramontina Vancouver em Aluminio com Revestimento Interno' , 219 , 'Corpo de aluminio com espessura de 3 , 2 mm que proporciona cozimento rapido e uniforme. Com revestimento interno e externo de antiaderente Starflon Max que nao gruda ,  e facil de limpar ,  mais duravel e nao e prejudicial a saude. Tampa de aluminio.  Altura: 22.90 cm. Largura: 23.10 cm. Diametro: 20 , 00 cm. Peso: 1.725 kg. Capacidade: 4.5 litros.');

-- Inserindo produto com status Inativo conforme regra n (13)
INSERT INTO MC_PRODUTO (CD_PRODUTO ,  CD_CATEGORIA ,  DS_PRODUTO ,  VL_UNITARIO ,  ST_PRODUTO  , DS_COMPLETA_PROD)
    VALUES (SQ_MC_PRODUTO.NEXTVAL , 13 , 'Amassador Batatas Legumes Espremedor Aco Inox Cabo Plastico' , 21.95 , 'I' , 'amassador Batatas Legumes Espremedor Aco Inox Cabo Plastico Cozinha Utilidade Domestica
    Amassador de Batatas em Aco Inox e Plastico O Amassador de batatas e o utensilio que falta em sua cozinha para facilitar sua vida no dia a dia. Este eficiente item vai ser de grande uso ,  facilitando na hora de preparar as refeicoes ,  feito de de aco inox material forte e duradouro foi feito para quem busca mais praticidade.Produto moderno multifuncional este amassador  super facil de usar , simples e eficiente ,  basta posiciona-lo sobre o que deseja amassar e pressionar para ter os seus alimentos prontos!Ideal para Batata ,  Legumes ,  Mandioca ,  Feijao.Dimencoes : 24.3 x 8 cmImagens meramente ilustrativas.');

COMMIT;

--j) Cadastre 2 vídeos de produtos na tabela MC_SGV_PRODUTO_VIDEO e associe esses 2 vídeos em um único produto já cadastrado. Associe também as categorias adequadas ao vídeo.

CREATE DIRECTORY video AS 'C:\app\lucas\product\21c\video';

DECLARE
    l_blob BLOB;
    l_file BFILE;
    l_file_len NUMBER;
BEGIN
    SELECT BFILENAME('VIDEO', 'S23.mp4') INTO l_file FROM DUAL;
    INSERT INTO MC_SGV_PRODUTO_VIDEO (CD_PRODUTO, NR_SEQUENCIA, CD_CATEGORIA, VD_PRODUTO, TP_VIDEO_PROD, DS_PATH_VIDEO_PROD, ST_VIDEO_PROD)
    VALUES (8, 1 , 14, EMPTY_BLOB(), 'Apresentar', 'https://www.youtube.com/watch?v=vAHRNElRBVY', 'A')
    RETURNING VD_PRODUTO INTO l_blob;
    
    l_file_len := DBMS_LOB.GETLENGTH(l_file);
    
    DBMS_LOB.OPEN(l_file, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.OPEN(l_blob, DBMS_LOB.LOB_READWRITE);
    
    DBMS_LOB.LOADFROMFILE(l_blob, l_file, l_file_len);
    
    DBMS_LOB.CLOSE(l_file);
    DBMS_LOB.CLOSE(l_blob);
    COMMIT;
END;

DECLARE
    l_blob BLOB;
    l_file BFILE;
    l_file_len NUMBER;
BEGIN
    SELECT BFILENAME('VIDEO', 'S23_Ultra.mp4') INTO l_file FROM DUAL;
    INSERT INTO MC_SGV_PRODUTO_VIDEO (CD_PRODUTO, NR_SEQUENCIA, CD_CATEGORIA, VD_PRODUTO, TP_VIDEO_PROD, DS_PATH_VIDEO_PROD, ST_VIDEO_PROD)
    VALUES (8, 2 , 14, EMPTY_BLOB(), 'Apresentar', 'https://www.youtube.com/watch?v=LSdkb6FyeOA', 'A')
    RETURNING VD_PRODUTO INTO l_blob;
    
    l_file_len := DBMS_LOB.GETLENGTH(l_file);
    
    DBMS_LOB.OPEN(l_file, DBMS_LOB.LOB_READONLY);
    DBMS_LOB.OPEN(l_blob, DBMS_LOB.LOB_READWRITE);
    
    DBMS_LOB.LOADFROMFILE(l_blob, l_file, l_file_len);
    
    DBMS_LOB.CLOSE(l_file);
    DBMS_LOB.CLOSE(l_blob);
    COMMIT;
END;

--k) Por fim, cadastre 5 visualizacoeses de videos de produtos na tabela MC_SGV_VISUALIZACAO_VIDEO e associe a um cliente a seu criterio.

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
    VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 1, 8, TO_DATE('15/04/2023', 'DD/MM/YYYY'), 15, 23, 19);

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
    VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 1, 10, TO_DATE('15/04/2023', 'DD/MM/YYYY'), 17, 14, 39);

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
    VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 1, 5, TO_DATE('16/04/2023', 'DD/MM/YYYY'), 08, 45, 13);

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
    VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 1, 4, TO_DATE('16/04/2023', 'DD/MM/YYYY'), 8, 53, 41);

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
    VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 1, 7, TO_DATE('17/04/2023', 'DD/MM/YYYY'), 13, 23, 36);

COMMIT;

--o) Selecione um específico funcionário e atualize o Cargo e aplique 12% de aumento de salário.
UPDATE MC_FUNCIONARIO
    SET VL_SALARIO = VL_SALARIO * 1.12, DS_CARGO = 'ANALISTA DE CONTABIL PLENO'
    WHERE CD_FUNCIONARIO = 6;
COMMIT;

--SELECT * FROM MC_FUNCIONARIO

--p) Atualize a descrição de uma categoria de produto a seu critério.
UPDATE MC_CATEGORIA_PROD
    SET DS_CATEGORIA = 'Produtos de audio, gravacao, transmissao e reproducao dos sons'
    WHERE CD_CATEGORIA = 2;
COMMIT;
--SELECT * FROM MC_CATEGORIA_PROD;

--q) Atualize o nome de um departamento a sua escolha, utilizando como filtro o nome do departamento antes de ser atualizado.
UPDATE MC_DEPTO
    SET NM_DEPTO = 'RH' 
    WHERE NM_DEPTO = 'RECURSOS HUMANOS - RH';
COMMIT;
--SELECT * FROM MC_DEPTO

--r) Atualize a data de nascimento de um cliente pessoa física. Defina a nova data como sendo 18/05/2002
UPDATE MC_CLI_FISICA
    SET DT_NASCIMENTO = TO_DATE('18/05/2002', 'DD/MM/YYYY')
    WHERE NR_CLIENTE = 7;
COMMIT;
--SELECT * FROM MC_CLI_FISICA

--s) Atualize a descricao de uma categoria de video a seu criterio.
UPDATE MC_CATEGORIA_PROD
    SET DS_CATEGORIA = 'Como sera utilizado o produto no cotidiano (Hands-on)'
    WHERE CD_CATEGORIA = 14;  
COMMIT;
--SELECT * FROM MC_CATEGORIA_PROD;

--t) Desative um funcionário colocando o status como I(nativo) e também a data de desligamento como sendo a data de hoje (sysdate).

UPDATE MC_FUNCIONARIO 
    SET  ST_FUNC = 'I' , DT_DESLIGAMENTO = TO_DATE (SYSDATE, 'DD/MM/YYYY')
    WHERE CD_FUNCIONARIO = 14;

COMMIT;

/*U - Cadastre um atendimento SAC na tabela MC_SGV_SAC. Apos isso, utilize outro comando DML para atualizar a descricao detalhada 
de retorno do SAC feito pelo funcionario. Insira um conteudo significativo. Nao se esqueca de atualizar tambem a data e hora 
de atendimento e tambem acrescendo o numero total de horas do atendimento SAC.
*/
INSERT INTO MC_SGV_SAC (NR_SAC, NR_CLIENTE, CD_PRODUTO, CD_FUNCIONARIO, DS_DETALHADA_SAC, DT_ABERTURA_SAC, HR_ABERTURA_SAC, DT_ATENDIMENTO, HR_ATENDIMENTO_SAC, 
NR_TEMPO_TOTAL_SAC, DS_DETALHADA_RETORNO_SAC, TP_SAC, ST_SAC, NR_INDICE_SATISFACAO)
VALUES (SQ_MC_SGV_SAC.NEXTVAL, 2, 8, 14, 'O celular e muito bom, mas demorou a chegar, poderiam melhorar o frete', TO_DATE('14/04/2023', 'DD/MM/YYYY'), 09, 
NULL, NULL, NULL, NULL, 'S', 'F', 7);
--Atualizando o atendimento
UPDATE MC_SGV_SAC
SET DS_DETALHADA_RETORNO_SAC = 'Foi feito  uma melhoria na logistica para atender melhor os clientes', DT_ATENDIMENTO = TO_DATE('14/04/2023', 'DD/MM/YYYY'), 
    HR_ATENDIMENTO_SAC = 13, NR_TEMPO_TOTAL_SAC = 4
WHERE NR_SAC = 1;

COMMIT;

--v) Selecione um endereço de cliente e coloque o status como I(nativo) e preencha a data de término como sendo a data de ontem. Utilize a função to_date para registrar esse novo valor da data.
--Atualizando status e data final para funcionario
UPDATE MC_END_FUNC 
    SET  ST_END = 'I' , DT_TERMINO = TO_DATE(SYSDATE-1,'DD/MM/YYYY')
    WHERE CD_FUNCIONARIO = 13;
COMMIT;
--SELECT * FROM MC_END_FUNC;

--w) Selecione um endereço de funcionário e coloque o status como I(nativo) e preencha a data de término como sendo a data de ontem. Utilize a função to_date para registrar esse novo valor da data.
--Atualizando status e data final para cliente
UPDATE MC_END_CLI 
    SET  ST_END = 'I' , DT_TERMINO = TO_DATE(SYSDATE-1,'DD/MM/YYYY')
    WHERE NR_CLIENTE = 1;
COMMIT;
--SELECT * FROM MC_END_CLI;

--x) Tente eliminar um estado que tenha uma cidade Cadastrada. Isso foi possível? Justifique o motivo?
 DELETE FROM MC_ESTADO
    WHERE SG_ESTADO = 'RN'; 

/*Não foi possivel eliminar a cidade cadastrada. Apresentou o erro conforme abaixo:

    --ORA-02292: restrição de integridade (RM99237.FK_MC_CIDADE_ESTADO) violada - registro filho localizado

    Este erro se da por conta da relação da MC_Cidade com a MC_Estado. Se eliminarmos a cidade, isto gerará 
inconsistencia no banco. Para conseguirmos apagar esta cidade devemos primeiro eliminar a relação.
*/

--y) Selecione um produto e tente atualizar o status do produto com o status X. Isso foi possível? Justifique o motivo?
 UPDATE MC_PRODUTO 
    SET  ST_PRODUTO = 'X'
    WHERE CD_PRODUTO = 1;  
/*Não foi possivel atualizar o status, pois a check Constraint impossibilitou isso. O status do produto pode ser somente 
(A)ativo e (I)inativo. O erro gerou conforme abaixo:
    --ORA-02290: restrição de verificação (C##TESTE.CK_MC_PRODUTO_ST_PRODUTO) violada

*/


--Deletando todo o conteudo da tabela MC_SGV_SAC 
--DELETE FROM MC_SGV_SAC;

 --Consultando todos os dados da tabela MC_SGV_SAC
--SELECT * FROM MC_SGV_SAC;

--Deletando todos os dasos da tabela MC_SGV_VISUAL_PROD
--DELETE FROM MC_SGV_VISUAL_PROD;

--Consultando todos os dados da tabela MC_SGV_VISUAL_PROD
--SELECT * FROM MC_SGV_VISUAL_PROD;

--Consultando todos os dados da tabela MC_SGV_VISUALIZACAO_VIDEO
--SELECT * FROM MC_SGV_VISUALIZACAO_VIDEO;

--Deletando todos os dados da tabela MC_SGV_PRODUTO_VIDEO
--DELETE FROM MC_SGV_PRODUTO_VIDEO;

--Consultando todos os dados da tabela MC_PRODUTO_VIDEO
--SELECT * FROM MC_SGV_PRODUTO_VIDEO;

--Deletar todos os dados da tabela MC_PRODUTO
--DELETE FROM MC_PRODUTO;

-- Consultando todos os dados da tabela MC_PRODUTO
--SELECT * FROM MC_PRODUTO;

--Comando utilizado para alterar a sequência durante o processo devido a erros no servidor em algumas tentativas de popular com produtos.
--ALTER SEQUENCE SQ_MC_PRODUTO RESTART START WITH 1;

--Deletar todos os dados de MC_CATEGORIA_PROD
--DELETE FROM MC_CATEGORIA_PROD;

-- Consultando todos os dados da tabela MC_CATEGORIA_PROD
--SELECT * FROM MC_CATEGORIA_PROD;

--Comando utilizado para alterar a sequência durante o processo devido a erros no servidor em algumas tentativas de popular as categorias.
--alter sequence SQ_MC_CATEGORIA restart start with 1;

--Deletar todos os dados de MC_CLIENTE
--DELETE FROM MC_CLIENTE;

--Deletar todos os dados de MC_CLI_FISICA
--DELETE FROM MC_CLI_FISICA;

--Deletar todos os dados de MC_CLI_JURIDICA
--DELETE FROM MC_CLI_JURIDICA;

-- Consultando todos os dados da tabela MC_CLIENTE
--SELECT * FROM MC_CLIENTE;

-- Consultando todos os dados da tabela MC_CLI_FISICA
--SELECT * FROM MC_CLI_FISICA;

-- Consultando todos os dados da tabela MC_CLI_JURIDICA
--SELECT * FROM MC_CLI_JURIDICA;

--Deletar todos os dados de MC_CLI_JURIDICA
--DELETE FROM MC_END_CLI;

-- Consultando todos os dados da tabela MC_CLI_JURIDICA
--SELECT * FROM MC_END_CLI;

--Deletando todos os dados da tabela MC_END_FUNC 
--DELETE FROM MC_END_FUNC

--Consultando todos os dados da tabela MC_END_FUNC
--SELECT * FROM MC_END_FUNC;

--Deletando todos os dados da tabela MC_LOGRADOURO 
--DELETE FROM MC_LOGRADOURO

--Consultando todos os dados da tabela MC_LOGRADOURO
--SELECT * FROM MC_LOGRADOURO

--Deleta todos os dados da tabela MC_BAIRRO 
--DELETE FROM MC_BAIRRO;

--Consultando todos os dados da tabela MC_BAIRRO
--SELECT * FROM MC_BAIRRO;

--Deletando todos os dados da tabela MC_CIDADE 
--DELETE FROM MC_CIDADE;

--Consultando todos os dados da tabela MC_CIDADE
--SELECT * FROM MC_CIDADE;

--Deletando todos os dados da tabela MC_ESTADOS 
--DELETE FROM MC_ESTADOS;

--Consultando todos os dados da tabela MC_ESTADO
--SELECT * FROM MC_ESTADO;

--Deletando todos os dados da tabela MC_FUNCIONARIO
--DELETE FROM MC_FUNCIONARIO;

--Consultando todos os dados da tabela MC_FUNCIONARIO
--SELECT * FROM MC_FUNCIONARIO;

--Deleta todods os dados da tabela MC_DEPTO
--DELETE FROM MC_DEPTO ;

--Consulta todos os dados da tabela MC_DEPTO
--SELECT * FROM MC_DEPTO;

