-- POPULAR A TABELA MC_ESTADO COM TODOS OS ESTADOS DO BRASIL

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('AC','Acre');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('AL','Alagoas');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('AP','Amapá');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('AM', 'Amazonas');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('BA', 'Bahia');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('CE', 'Ceará');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('ES', 'Espírito Santo');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('GO', 'Goiás');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('MA', 'Maranhão');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('MT', 'Mato Grosso');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('MS', 'Mato Grosso do Sul');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('MG', 'Minas Gerais');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('PA', 'Pará');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('PB', 'Paraíba');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('PR', 'Paraná');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('PE', 'Pernambuco');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('PI', 'Piauí');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('RJ', 'Rio de Janeiro');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('RN', 'Rio Grande do Norte');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('RS', 'Rio Grande do Sul');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('RO', 'Rondônia');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('RR', 'Roraima');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('SC', 'Santa Catarina');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('SP', 'São Paulo');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('SE', 'Sergipe');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('TO', 'Tocantins');
INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
VALUES ('DF', 'Distrito Federal');


















