-- POPULAR A TABELA MC_DEPTO INSERINDO NO MINIMO 7 DEPARTAMENTOS

--Inserindo o Departamento Comercial
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'COMERCIAL', 'A');
--Inserindo o Departamento Contabilidade
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'CONTABILIDADE', 'A');
--Inserindo o Departamento Estoque
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'ESTOQUE', 'A');
--Inserindo o Departamento Financeiro
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'FINANCEIRO', 'A');
--Inserindo o Departamento Serviço de Atendimento ao cliente - SAC
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'SERVIÇO DE ATENDIMENTO AO CLIENTE - SAC', 'A');
--Inserindo o Departamento Recursos Humanos - RH
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'RECURSOS HUMANOS - RH','A');
--Inserindo o Departamento Logistica
INSERT INTO MC_DEPTO(CD_DEPTO, NM_DEPTO, ST_DEPTO) 
VALUES (SQ_MC_DEPTO.NEXTVAL, 'LOGISTICA', 'A');

--Deleta todods os dados da tabela MC_DEPTO
DELETE FROM MC_DEPTO ;

--Consulta todos os dados da tabela MC_DEPTO
SELECT * FROM MC_DEPTO;
