/* Para cada cidade, associe no mínimo 1 bairro e para cada bairro, associe 
2 endereços. Utilize nomes significativos e coerentes, de acordo com a base 
do Correio*/ 

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 1, 'JARDIM SAO JOSE', 'ZONA SUL');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 1, 'PARQUE SAO QUIRINO', 'ZONA NORTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 2, 'VISTA VERDE', 'ZONA NORTE');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 2, 'JARDIM COLONIAL', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 3, 'PLANALTO VERDE', 'ZONA OESTE');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 3, 'NOVA ALIANÇA', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 4, 'ALVORADA', 'ZONA LESTE');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 4, 'TOCANTINS', 'ZONA OESTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 5, 'PAMPULHA', 'ZONA NORTE');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 5, 'DISTRITO INDUSTRIAL DO JATOBÁ', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 6,'SANTA LUZIA', 'ZONA SUL');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 6,'ENCOSTA DO SOL', 'ZONA OESTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 7,'KENNEDY', 'ZONA OESTE');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 7,'MAURICIO DE NASSAU', 'CENTRO');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 8,'PINA', 'ZONA SUL');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 8,'BAIRRO DO RECIFE', 'CENTRO');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 9,'DOM AVELAR', 'ZONA NORTE');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 9,'SÃO GONÇALO', 'ZONA OESTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 10,'PONTA NEGRA', 'ZONA SUL');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 10,'TIROL', 'CENTRO');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 11,'ALTO SUMARÉ', 'ZONA SUL');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 11,'RINCÃO', 'ZONA LESTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 12,'CENTRO', 'ZONA CENTRAL');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 12,'NOVA PARNAMIRIM', 'ZONA LESTE');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 13,'PARQUE GUARANI', 'ZONA SUL');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 13,'AVENTUREIRO', 'ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 14,'PRAIA BRAVA','ZONA NORTE');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 14,'CAMPECHE','ZONA SUL');

INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 15,'BARRA', 'ZONA SUL');
INSERT INTO MC_BAIRRO (CD_BAIRRO, CD_CIDADE, NM_BAIRRO, NM_ZONA_BAIRRO) 
VALUES (SQ_MC_BAIRRO.NEXTVAL, 15,'PIONEIROS', 'ZONA NORTE');


COMMIT;
--Deletando todos os dados da tabela MC_BAIRRO 
--DELETE FROM MC_BAIRRO;

--Consultando todos os dados da tabela MC_BAIRRO
SELECT * FROM MC_BAIRRO;




