-- c) parte 4: PARA CADA BAIRRO , ASSOCIE 2 ENDERE�OS. 

INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 1 , 'RUA RODOLFO PANONI , 249' , 13051170)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 1 , 'RUA MIGUEL JO�O JORGE , 129' , 13051172)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 2 , 'RUA LU�S PAOLIERI , 112' , 13088390)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 2 , 'RUA CYRENIA ARRUDA CAMARGO , 1211' , 13088106)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 3 , 'RUA ARUBA , 74' , 12223780)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 3 , 'RUA BAVIERA , 333' , 12223760)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 4 , 'RUA CELINA , 223' , 12234360)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 4 , 'RUA BALTAZAR , 245' , 12234360)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 5 , 'RUA ALEXANDRE SETI , 160' , 14056604)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 5 , 'RUA JOAQUIM LEONARDO , 251' , 14056603)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 6 , 'RUA JOS� JAIME DELIBO , 90' , 14026563)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 6 , 'RUA PEDRO GIROTO , 2' , 14026560)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 7 , 'RUA JO�O AUGUSTO LOPES , 212' , 38407072)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 7 , 'RUA MARIA AUGUSTA MORAIS , 82' , 38407069)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 8 , 'RUA AGENOR BORGES , 303' , 38415321)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 8 , 'RUA JOAQUIM CARRIJO NETTO , 253' , 38415360)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 9 , 'RUA L�DER , 22' , 31270480)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 9 , 'RUA PROF. NELSON DE SENA , 88' , 31270383)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 10 , 'RUA VALE DO IP� , 222' , 30666470)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 10 , 'RUA ZUMBI DOS PALMARES , 33' , 30666475)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 11 , 'RUA IBITIGUAIA , 781' , 36031000)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 11 , 'RUA HUMBERTO BERZOINI , 242' , 36031060)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 12 , 'RUA ENG. REGINALDO ARCURI , 96' , 36083018)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 12 , 'RUA POETA DALTEMAR LIMA , 2' , 36083015)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 13 , 'RUA CADENTE , 16' , 55780000)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 13 , 'RUA MERC�RIO , 12' , 55040260)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 14 , 'AVENIDA OSWALDO CRUZ , 275' , 55012040)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 14 , 'RUA TE�FILO DIAS , 27' , 55012710)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 15 , 'RUA TOM� GIBSON , 32' , 51011480)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 15 , 'RUA AMAZONAS , 171' , 51011020)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 16 , 'RUA DO BOM JESUS , 14' , 50030170)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 16 , 'RUA MADRE DE DEUS , 171' , 50030230)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 17 , 'RUA DA AMIZADE , 30' , 56323130)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 17 , 'AVENIDA DA ESPERAN�A , 650' , 56323140)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 18 , 'RUA VINTE E OITO , 75' , 56312281)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 18 , 'RUA SILVESTRE DIAS PINHEIRO , 132' , 56312285)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 19 , 'RUA ERIVAN FRAN�A , 153' , 59090100)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 19 , 'RUA PEDRO FONSECA FILHO , 2030' , 59090080)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 20 , 'RUA CEAR� MIRIM , 378' , 59020240)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 20 , 'RUA JOS� MARTINS BEZERRA , 13' , 59020215)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 21 , 'RUA SABI� , 121' , 59632140)
      
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 21 , 'RUA ZEUS , 399' , 59632215)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 22 , 'RUA ANTONIO JOS� DE LIMA , 409' , 59630508)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 22 , 'RUA SERGINA LUCINDA ALVES , 367' , 59630640)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 23 , 'RUA EDGAR DANTAS , 42' , 59140290)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 23 , 'RUA TENENTE OS�RIO , 1999' , 59140285)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 24 , 'RUA DAS AMORAS , 54' , 59152675)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 24 , 'RUA SERRA DO CARMO , 51' , 59152698)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 25 , 'RUA LOURIVAL LEITE PALHARES , 52' , 89209550)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 25 , 'RUA HERM�NIO PICOLLI , 12' , 89209615)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 26 , 'RUA UIRAPURU , 100' , 89225680)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 26 , 'RUA ARARA , 485' , 89226010)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 27 , 'RUA CARLOS DA COSTA PEREIRA , 2' , 88056810)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 27 , 'RUA NICOLINO TANCREDO , 322' , 88056840)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 28 , 'RUA DAS CORTICEIRAS , 466' , 88063160)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 28 , 'RUA JARDIM DOS EUCALIPTOS , 800' , 88063270)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 29 , 'RUA PEDRO PINTO CORR�A , 214' , 88332240)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 29 , 'RUA BENTO CUNHA , 549' , 88332170)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 30 , 'RUA ROMEU PEREIRA , 23' , 88331045)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 30 , 'RUA MIGUEL MATTE , 376' , 88331030)
    
COMMIT;
--Deletando todos os dados da tabela MC_LOGRADOURO 
--DELETE FROM MC_LOGRADOURO

--Consultando todos os dados da tabela MC_LOGRADOURO
--SELECT * FROM MC_LOGRADOURO