/*d) Por fim, cadastre na tabela de ENDERECO FUNCIONARIO todos os funcion�rios com no m�nimo 1 endere�o para cada um. 
Escolha v�rios estados do Brasil, ou seja, um funcion�rio pode residir em mais de uma localidade, dado que a empresa 
Melhores Compras incentiva o trabalho em formato home office. 
*/

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (1,60,376,'RUA MIGUEL MATTE', TO_DATE('10/10/2000','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(2,59,23,	'RUA ROMEU PEREIRA',TO_DATE('18/07/2008','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(3,58,549,'RUA BENTO CUNHA', TO_DATE('31/03/2009', 'DD/MM/YYYY'), NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(4,57,214,'RUA PEDRO PINTO CORR�A',TO_DATE('31/03/1990', 'DD/MM/YYYY'), NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(5,56,800,'RUA JARDIM DOS EUCALIPTOS',TO_DATE('31/08/2011','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(6,55,466,'RUA DAS CORTICEIRAS',TO_DATE('21/07/2010','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(7,54,322,'RUA NICOLINO TANCREDO',TO_DATE('14/06/2011','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(8,53,2,'RUA CARLOS DA COSTA PEREIRA',TO_DATE('18/05/1991', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(9,52,485,'RUA ARARA',TO_DATE('18/05/2005','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(10,51,100,'RUA UIRAPURU',TO_DATE('23/09/2009', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(11,50,12,'RUA HERM�NIO PICOLLI',	TO_DATE('20/11/2006', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(12,49,52,'RUA LOURIVAL LEITE PALHARES',	TO_DATE('20/11/1992', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(13,48,51,'RUA SERRA DO CARMO',TO_DATE('10/02/1997', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(14,47,54,'RUA DAS AMORAS',TO_DATE('17/06/2006','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(15,46,1999,'RUA TENENTE OS�RIO',TO_DATE('18/09/2012', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (16,45,42,'RUA EDGAR DANTAS',TO_DATE('18/05/2005','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(17,44,367,'RUA SERGINA LUCINDA ALVES',TO_DATE('18/05/2005','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(18,43,409,'RUA ANTONIO JOS� DE LIMA',TO_DATE('18/05/2005', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(19,42,399,'RUA ZEUS',TO_DATE('18/05/2005','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(20,41,121,'RUA SABI�',TO_DATE('18/05/2005','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(21,4,13,'RUA JOS� MARTINS BEZERRA',TO_DATE('18/05/2005','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(22,39,378, 'RUA CEAR� MIRIM',TO_DATE('18/05/2005','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (23,38,2030,'RUA PEDRO FONSECA FILHO',TO_DATE('18/05/2005', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (24,37,153,'RUA ERIVAN FRAN�A',	TO_DATE('15/02/2008', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(25,36,132,'RUA SILVESTRE DIAS PINHEIRO',	TO_DATE('15/02/2023', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(26,35,75,'RUA VINTE E OITO',	TO_DATE('15/02/2023', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(27,34,650,'AVENIDA DA ESPERAN�A',TO_DATE('15/02/2023', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(28,33,30,'RUA DA AMIZADE',TO_DATE('15/02/2005','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(29,32,171,'RUA MADRE DE DEUS', TO_DATE('15/02/2023','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(30,31,14,'RUA DO BOM JESUS',	TO_DATE('15/02/2023', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(31,30,171,'RUA AMAZONAS',TO_DATE('18/02/2021','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(32,29,32,'RUA TOM� GIBSON',TO_DATE('15/02/2010','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(33,28,27,'RUA TE�FILO DIAS',	TO_DATE('02/11/2018','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(34,27,275,'AVENIDA OSWALDO CRUZ',TO_DATE('02/07/2017','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(35,26,12,'RUA MERC�RIO',	TO_DATE('15/02/2014','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(36,25,16,'RUA CADENTE',TO_DATE('16/02/2009','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(37,24,2,'RUA POETA DALTEMAR LIMA',TO_DATE('25/02/2009','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(38,23,96,'RUA ENG. REGINALDO ARCURI',TO_DATE('21/06/2012','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(39,	22,	242,'RUA HUMBERTO BERZOINI',TO_DATE('25/02/2009','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(40,21,781,'RUA IBITIGUAIA',TO_DATE('9/4/2010','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(41,20,33,'RUA ZUMBI DOS PALMARES',TO_DATE('7/3/2010','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(42,19,222,'RUA VALE DO IP�',	TO_DATE('8/9/2015','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(43,18,88,'RUA PROF. NELSON DE SENA',	TO_DATE('9/8/2018','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(44,17,22,'RUA L�DER',TO_DATE('1/2/2005','DD/MM/YYYY'),NULL, 'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(45,16,253,'RUA JOAQUIM CARRIJO NETTO',TO_DATE('9/8/2022', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(46,15,303,'RUA AGENOR BORGES',TO_DATE('1/2/2000','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(47,14,82,'RUA MARIA AUGUSTA MORAIS',	TO_DATE('1/2/2000', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(48,13,212,'RUA JO�O AUGUSTO LOPES',TO_DATE('1/2/2005', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(49,12,2,'RUA PEDRO GIROTO',	TO_DATE('1/2/2006', 'DD/MM/YYYY'),NULL,	'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(50,11,90,'RUA JOS� JAIME DELIBO',TO_DATE('2/1/2006', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(51,10,251,'RUA JOAQUIM LEONARDO',TO_DATE('2/1/2006', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(1,9,160,	'RUA ALEXANDRE SETI',TO_DATE('10/10/2000','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(2,8,245,'RUA BALTAZAR',TO_DATE('18/07/2008', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(3,7,223, 'RUA CELINA',TO_DATE('31/3/2009', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(4,6,333,'RUA BAVIERA',TO_DATE('31/3/1990', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(5,5,74,'RUA ARUBA',TO_DATE('31/08/2011', 'DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(6,4,1211,'RUA CYRENIA ARRUDA CAMARGO',TO_DATE('21/07/2010','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(7,3,112,	'RUA LU�S PAOLIERI',TO_DATE('14/06/2011','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(8,2,129,	'RUA MIGUEL JO�O JORGE',TO_DATE('18/05/1991','DD/MM/YYYY'),NULL,'A');

INSERT INTO MC_END_FUNC (CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES(9,1,249,	'RUA RODOLFO PANONI',TO_DATE('18/05/2005','DD/MM/YYYY'),NULL,'A');

COMMIT;
--Deletando todos os dados da tabela MC_END_FUNC 
--DELETE FROM MC_END_FUNC

--Consultando todos os dados da tabela MC_END_FUNC
--SELECT * FROM MC_END_FUNC;