/*d) Por fim, cadastre na tabela de ENDERECO FUNCIONARIO todos os funcion�rios com no m�nimo 1 endere�o para cada um. 
Escolha v�rios estados do Brasil, ou seja, um funcion�rio pode residir em mais de uma localidade, dado que a empresa 
Melhores Compras incentiva o trabalho em formato home office. 
*/

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (1 , 60 , 376 , 'CASA' , TO_DATE('10/10/2000','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (2 , 59 , 23 , 'CASA' , TO_DATE('18/07/2008','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (3 , 58 , 549 , 'CASA' , TO_DATE('31/03/2009','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (4 , 57 , 214 , 'CASA' , TO_DATE('31/03/1990','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (5 , 56 , 800 , 'APARTAMENTO 10' , TO_DATE('31/08/2011','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (6 , 55 , 466 , 'CASA 2' , TO_DATE('21/07/2010','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (7 , 54 , 322 , 'EM FRENTE A PIZZARIA ROMANA' , TO_DATE('14/06/2011','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (8 , 53 , 2 , 'APARTAMENTO 70' , TO_DATE('18/05/1991','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (9 , 52 , 485 , 'APARTAMENTO A BLOCO B' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (10 , 51 , 100 , 'APARTAMENTO 100' , TO_DATE('23/09/2009','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (11 , 50 , 12 , 'APARTAMENTO A BLOCO C' , TO_DATE('20/11/2006','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (12 , 49 , 52 , 'CASA SEGUNDO ANDAR' , TO_DATE('20/11/1992','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (13 , 48 , 51 , 'CASA' , TO_DATE('10/02/1997','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (14 , 47 , 54 , 'CASA' , TO_DATE('17/06/2006','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (15 , 46 , 1999 , 'CASA' , TO_DATE('18/09/2012','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (16 , 45 , 42 , 'CASA' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (17 , 44 , 367 , 'CASA' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (18 , 43 , 409 , 'CASA' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (19 , 42 , 399 , 'CASA' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (20 , 41 , 121 , 'CASA' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (21 , 4 , 13 , 'CASA' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (22 , 39 , 378 , 'BLOCO A CASA 10' , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (23 , 38 , 2030 , NULL , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (24 , 37 , 153 , NULL , TO_DATE('15/02/2008','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (25 , 36 , 132 , NULL , TO_DATE('15/02/2023','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (26 , 35 , 75 , NULL , TO_DATE('15/02/2023','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (27 , 34 , 650 , 'AP 2062' , TO_DATE('15/02/2023','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (28 , 33 , 30 , NULL , TO_DATE('15/02/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (29 , 32 , 171 , NULL , TO_DATE('15/02/2023','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (30 , 31 , 14 , NULL , TO_DATE('15/02/2023','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (31 , 30 , 171 , NULL , TO_DATE('18/02/2021','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (32 , 29 , 32 , NULL , TO_DATE('15/02/2010','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (33 , 28 , 27 , 'BLOCO A CASA 20' , TO_DATE('02/11/2018','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (34 , 27 , 275 , NULL , TO_DATE('02/07/2017','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (35 , 26 , 12 , 'APTO 1806' , TO_DATE('15/02/2014','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (36 , 25 , 16 , NULL , TO_DATE('16/02/2009','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (37 , 24 , 2 , NULL , TO_DATE('25/02/2009','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (38 , 23 , 96 , NULL , TO_DATE('21/06/2012','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (39 , 22 , 242 , 'CASA' , TO_DATE('25/02/2009','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (40 , 21 , 781 , 'CASA' , TO_DATE('09/04/2010','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (41 , 20 , 33 , 'CASA' , TO_DATE('07/03/2010','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (42 , 19 , 222 , 'CASA' , TO_DATE('08/09/2015','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (43 , 18 , 88 , 'CASA' , TO_DATE('09/08/2018','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (44 , 17 , 22 , 'CASA' , TO_DATE('01/02/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (45 , 16 , 253 , 'CASA' , TO_DATE('09/08/2022','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (46 , 15 , 303 , NULL , TO_DATE('01/02/2000','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (47 , 14 , 82 , NULL , TO_DATE('01/02/2000','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (48 , 13 , 212 , NULL , TO_DATE('01/02/2005','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (49 , 12 , 2 , NULL , TO_DATE('01/02/2006','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (50 , 11 , 90 , NULL , TO_DATE('02/01/2006','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (51 , 10 , 251 , NULL , TO_DATE('02/01/2006','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (1 , 9 , 160 , NULL , TO_DATE('10/10/2000','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (2 , 8 , 245 , NULL , TO_DATE('18/07/2008','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (3 , 7 , 223 , NULL , TO_DATE('31/03/2009','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (4 , 6 , 333 , NULL , TO_DATE('31/03/1990','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (5 , 5 , 74 , NULL , TO_DATE('31/08/2011','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (6 , 4 , 1211 , 'CASA' , TO_DATE('21/07/2010','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (7 , 3 , 112 , 'CASA' , TO_DATE('14/06/2011','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (8 , 2 , 129 , 'CASA' , TO_DATE('18/05/1991','DD/MM/YYYY') ,NULL ,'A');

INSERT INTO MC_END_FUNC(CD_FUNCIONARIO, CD_LOGRADOURO, NR_END, DS_COMPLEMENTO_END, DT_INICIO, DT_TERMINO,ST_END)
    VALUES (9 , 1 , 249 , NULL , TO_DATE('18/05/2005','DD/MM/YYYY') ,NULL ,'A');

COMMIT;
--Deletando todos os dados da tabela MC_END_FUNC 
--DELETE FROM MC_END_FUNC

--Consultando todos os dados da tabela MC_END_FUNC
--SELECT * FROM MC_END_FUNC;