--k) Por fim, cadastre 5 visualizacoeses de videos de produtos na tabela MC_SGV_VISUALIZACAO_VIDEO e associe a um cliente a seu criterio.

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
    VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 1, 8, TO_DATE('15/04/2023', 'DD/MM/YYYY'), 15, 23, 19);

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
    VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 1, 10, TO_DATE('15/04/2023', 'DD/MM/YYYY'), 17, 14, 39);

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
    VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 1, 5, TO_DATE('16/04/2023', 'DD/MM/YYYY'), 08, 45, 13);

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
    VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 1, 4, TO_DATE('16/04/2023', 'DD/MM/YYYY'), 8, 53, 41);

INSERT INTO MC_SGV_VISUALIZACAO_VIDEO (CD_VISUALIZACAO_VIDEO, NR_CLIENTE, CD_PRODUTO, DT_VISUALIZACAO, NR_HORA_VISUALIZACAO, NR_MINUTO_VIDEO, NR_SEGUNDO_VIDEO)
    VALUES (SQ_MC_SGV_VISUAL_PROD.NEXTVAL, 1, 7, TO_DATE('17/04/2023', 'DD/MM/YYYY'), 13, 23, 36);

COMMIT;

--Deletando todos os dasos da tabela MC_SGV_VISUAL_PROD
--DELETE FROM MC_SGV_VISUAL_PROD;


--SELECT * FROM MC_SGV_VISUAL_PROD;
SELECT * FROM MC_SGV_VISUALIZACAO_VIDEO;