-- c) Parte 1: POPULAR A TABELA MC_ESTADO COM TODOS OS ESTADOS DO BRASIL

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('AC','Acre');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('AL','Alagoas');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('AP','Amapa');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('AM', 'Amazonas');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('BA', 'Bahia');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('CE', 'Ceara');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('ES', 'Espirito Santo');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('GO', 'Goias');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('MA', 'Maranhao');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('MT', 'Mato Grosso');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('MS', 'Mato Grosso do Sul');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('MG', 'Minas Gerais');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('PA', 'Para');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('PB', 'Paraiba');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('PR', 'Parana');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('PE', 'Pernambuco');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('PI', 'Piaui');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('RJ', 'Rio de Janeiro');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('RN', 'Rio Grande do Norte');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('RS', 'Rio Grande do Sul');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('RO', 'Rondonia');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('RR', 'Roraima');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('SC', 'Santa Catarina');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('SP', 'Sao Paulo');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('SE', 'Sergipe');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('TO', 'Tocantins');

INSERT INTO MC_ESTADO(SG_ESTADO, NM_ESTADO)
    VALUES ('DF', 'Distrito Federal');

COMMIT;


--Deletando todos os dados da tabela MC_ESTADOS 
--DELETE FROM MC_ESTADOS;

--Consultando todos os dados da tabela MC_ESTADO
--SELECT * FROM MC_ESTADO;