-- c) parte 4: PARA CADA BAIRRO , ASSOCIE 2 ENDERECOS. 

INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 1 , 'RUA RODOLFO PANONI' , 13051170)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 1 , 'RUA MIGUEL JOAO JORGE' , 13051172)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 2 , 'RUA LUIS PAOLIERI' , 13088390)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 2 , 'RUA CYRENIA ARRUDA CAMARGO' , 13088106)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 3 , 'RUA ARUBA' , 12223780)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 3 , 'RUA BAVIERA' , 12223760)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 4 , 'RUA CELINA' , 12234360)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 4 , 'RUA BALTAZAR' , 12234360)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 5 , 'RUA ALEXANDRE SETI' , 14056604)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 5 , 'RUA JOAQUIM LEONARDO' , 14056603)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 6 , 'RUA JOSE JAIME DELIBO' , 14026563)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 6 , 'RUA PEDRO GIROTO' , 14026560)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 7 , 'RUA JOAO AUGUSTO LOPES' , 38407072)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 7 , 'RUA MARIA AUGUSTA MORAIS' , 38407069)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 8 , 'RUA AGENOR BORGES' , 38415321)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 8 , 'RUA JOAQUIM CARRIJO NETTO' , 38415360)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 9 , 'RUA LIDER' , 31270480)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 9 , 'RUA PROF. NELSON DE SENA' , 31270383)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 10 , 'RUA VALE DO IPE' , 30666470)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 10 , 'RUA ZUMBI DOS PALMARES' , 30666475)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 11 , 'RUA IBITIGUAIA' , 36031000)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 11 , 'RUA HUMBERTO BERZOINI' , 36031060)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 12 , 'RUA ENG. REGINALDO ARCURI' , 36083018)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 12 , 'RUA POETA DALTEMAR LIMA' , 36083015)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 13 , 'RUA CADENTE' , 55780000)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 13 , 'RUA MERCURIO' , 55040260)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 14 , 'AVENIDA OSWALDO CRUZ' , 55012040)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 14 , 'RUA TEOFILO DIAS' , 55012710)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 15 , 'RUA TOME GIBSON' , 51011480)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 15 , 'RUA AMAZONAS' , 51011020)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 16 , 'RUA DO BOM JESUS' , 50030170)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 16 , 'RUA MADRE DE DEUS' , 50030230)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 17 , 'RUA DA AMIZADE' , 56323130)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 17 , 'AVENIDA DA ESPERANCA' , 56323140)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 18 , 'RUA VINTE E OITO' , 56312281)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 18 , 'RUA SILVESTRE DIAS PINHEIRO' , 56312285)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 19 , 'RUA ERIVAN FRANCA' , 59090100)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 19 , 'RUA PEDRO FONSECA FILHO' , 59090080)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 20 , 'RUA CEARA MIRIM' , 59020240)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 20 , 'RUA JOSE MARTINS BEZERRA' , 59020215)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 21 , 'RUA SABIA' , 59632140)
      
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 21 , 'RUA ZEUS' , 59632215)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 22 , 'RUA ANTONIO JOSE DE LIMA' , 59630508)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 22 , 'RUA SERGINA LUCINDA ALVES' , 59630640)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 23 , 'RUA EDGAR DANTAS' , 59140290)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 23 , 'RUA TENENTE OSORIO' , 59140285)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 24 , 'RUA DAS AMORAS' , 59152675)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 24 , 'RUA SERRA DO CARMO' , 59152698)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 25 , 'RUA LOURIVAL LEITE PALHARES' , 89209550)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 25 , 'RUA HERMINIO PICOLLI' , 89209615)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 26 , 'RUA UIRAPURU' , 89225680)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 26 , 'RUA ARARA' , 89226010)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 27 , 'RUA CARLOS DA COSTA PEREIRA' , 88056810)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 27 , 'RUA NICOLINO TANCREDO' , 88056840)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 28 , 'RUA DAS CORTICEIRAS' , 88063160)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 28 , 'RUA JARDIM DOS EUCALIPTOS' , 88063270)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 29 , 'RUA PEDRO PINTO CORREA' , 88332240)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 29 , 'RUA BENTO CUNHA' , 88332170)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 30 , 'RUA ROMEU PEREIRA' , 88331045)
    
INSERT INTO MC_LOGRADOURO(CD_LOGRADOURO , CD_BAIRRO , NM_LOGRADOURO , NR_CEP)
    VALUES (SQ_MC_LOGRADOURO.NEXTVAL , 30 , 'RUA MIGUEL MATTE' , 88331030)
    
COMMIT;
--Deletando todos os dados da tabela MC_LOGRADOURO 
--DELETE FROM MC_LOGRADOURO

--Consultando todos os dados da tabela MC_LOGRADOURO
--SELECT * FROM MC_LOGRADOURO