--POPULANDO TABELA SAC PARA REALIZAÇÃO DE TESTES.
INSERT INTO MC_SGV_SAC(NR_SAC, NR_CLIENTE, CD_PRODUTO, CD_FUNCIONARIO,  DS_DETALHADA_SAC, DT_ABERTURA_SAC, HR_ABERTURA_SAC, DT_ATENDIMENTO, HR_ATENDIMENTO_SAC, DS_DETALHADA_RETORNO_SAC, TP_SAC, ST_SAC)
    VALUES(SQ_MC_SGV_SAC.NEXTVAL,2,12,37,'Jogo não roda no meu PS10.', TO_DATE('01/04/2023','DD/MM/YYYY'),8,TO_DATE('01/04/2023','DD/MM/YYYY'),9,'Foi orientado o cliente a soprar suavemente o cd e tentar novamente.','D','E');

INSERT INTO MC_SGV_SAC(NR_SAC, NR_CLIENTE, CD_PRODUTO, CD_FUNCIONARIO,  DS_DETALHADA_SAC, DT_ABERTURA_SAC, HR_ABERTURA_SAC, DT_ATENDIMENTO, HR_ATENDIMENTO_SAC, DS_DETALHADA_RETORNO_SAC, TP_SAC, ST_SAC)
    VALUES(SQ_MC_SGV_SAC.NEXTVAL,3,4,37,'Celular travando com frequência.', TO_DATE('03/05/2023','DD/MM/YYYY'),11,TO_DATE('03/05/2023','DD/MM/YYYY'),12,'Foi esclaredico ao cliente que é normal da marca do aparelho.','D','E');

INSERT INTO MC_SGV_SAC(NR_SAC, NR_CLIENTE, CD_PRODUTO, CD_FUNCIONARIO,  DS_DETALHADA_SAC, DT_ABERTURA_SAC, HR_ABERTURA_SAC, DT_ATENDIMENTO, HR_ATENDIMENTO_SAC, DS_DETALHADA_RETORNO_SAC, TP_SAC, ST_SAC)
    VALUES(SQ_MC_SGV_SAC.NEXTVAL,7,2,38,'Meias super confortáveis.', TO_DATE('10/05/2023','DD/MM/YYYY'),15,TO_DATE('10/05/2023','DD/MM/YYYY'),16,'Elogio registrado no SAC e destacado nos comentário dos produtos.','E','E');

