SET SERVEROUTPUT ON;

DECLARE
--CRIACAO DO CURSOR SAC CONTENDO TODOS OS CAMPOS DESCRITOS NA ALTERNATIVA A
   CURSOR SAC IS
         SELECT S.NR_SAC, S.DT_ABERTURA_SAC, S.HR_ABERTURA_SAC, S.TP_SAC,
                P.CD_PRODUTO, P.DS_PRODUTO, P.VL_UNITARIO, P.VL_PERC_LUCRO,
                C.NR_CLIENTE, C.NM_CLIENTE
          FROM MC_SGV_SAC S INNER JOIN MC_PRODUTO P
            ON(S.NR_SAC = P.CD_PRODUTO) 
          INNER JOIN MC_CLIENTE C
            ON (S.NR_SAC = C.NR_CLIENTE);
            
 --Variavel V_TP_SAC CRIADA PARA ARMAZENAR O CONTEUDO QUE VAI NA DESCRIÇÃO DO SAC (DUVIDA, SUGESTAO OU ELOGIO), ONDE SERÁ DEFINIDA NO IF DENTRO DO FOR            
    V_TP_SAC  MC_SGV_SAC.TP_SAC%TYPE;
--VARIAVEL CRIADA PARA ARMAZENAR O LUCRO DO PROCUTO COMO PEDE O ENUNCIADO. "EU NÃO TESTEI E NÃO SEI SE ESTA CERTO"    
    V_LUCRO_PRODUTO FLOAT(10) := (P.VL_PERC_LUCRO /100) * P.VL_UNITARIO;
BEGIN

    
    FOR S IN SAC LOOP
--IF PRA VER QUAL É O TIPO DO SAC(DUVIDA, SUGESTÃO OU ELOGIO)
         IF  S.TP_SAC = 'D' THEN
             V_TP_SAC = 'DUVIDA';
         ELSIF S.TP_SAC = 'S' THEN
             V_TP_SAC = 'SUGESTAO';
         ELSIF S.TP_SAC = 'E' THEN
             V_TP_SAC = 'ELOGIO';
         ELSE
             V_TP_SAC = 'CLASSIFICACAO INVALIDA';
        
        END IF;
 --INSERINDO OS DADOS DA TABELA DE OCORRENCIA. "AINDA FALTA DADOS PARA SEREM INSERIDOS, EU PAREI NO LUCRO DO PRODUTO. FAVOR ANALISAR"
             INSERT INTO MC_SGV_OCORRENCIA_SAC (NR_OCORRENCIA_SAC, DT_ABERTURA_SAC, HR_ABERTURA_SAC, DS_TIPO_CLASSIFICACAO_SAC, CD_PRODUTO, VL_UNITARIO_PRODUTO, 
                                                VL_PERC_LUCRO, VL_UNITARIO_LUCRO_PRODUTO, SG_ESTADO, NM_ESTADO, NR_CLIENTE, NM_CLIENTE, VL_ICMS_PRODUTO)
             VALUES(S.NR_SAC, S.DT_ABERTURA, S.HR_ABERTURA, V_TP_SAC, S.CD_PRODUTO, S.VL_UNITARIO, S.VL_PERC_LUCRO, V_LUCRO_PRODUTO, )
        
       
    END LOOP;

END;
/





--AQUI É SO ALGUNS SELECTS PRA EU VER O NOME DOS CAMPOS E A ESTRUTURA DAS TABELAS  PRA FAZER O CURSOR E O INSERT. 
DESC MC_SGV_OCORRENCIA_SAC;

    
SELECT * FROM MC_SGV_SAC;
SELECT * FROM MC_PRODUTO;
SELECT * FROM MC_CLIENTE;
SELECT * FROM MC_SGV_OCORRENCIA_SAC;
SELECT * FROM MC_ESTADO;
SELECT * FROM MC_END_CLI;