SET SERVEROUTPUT ON;

DECLARE
--CRIACAO DO CURSOR SAC CONTENDO TODOS OS CAMPOS DESCRITOS NA ALTERNATIVA A
   CURSOR SAC IS
         SELECT S.NR_SAC, S.DT_ABERTURA_SAC, S.HR_ABERTURA_SAC, S.TP_SAC,
                P.CD_PRODUTO, P.DS_PRODUTO, P.VL_UNITARIO, P.VL_PERC_LUCRO,
                C.NR_CLIENTE, C.NM_CLIENTE
                FROM MC_SGV_SAC S INNER JOIN MC_PRODUTO P
            ON(S.NR_SAC = P.CD_PRODUTO) 
          INNER JOIN MC_CLIENTE C
            ON (S.NR_SAC = C.NR_CLIENTE);
            
 --Variavel V_TP_SAC CRIADA PARA ARMAZENAR O CONTEUDO QUE VAI NA DESCRIÇÃO DO SAC (DUVIDA, SUGESTAO OU ELOGIO), ONDE SERÁ DEFINIDA NO IF DENTRO DO FOR            
    V_TP_SAC  MC_SGV_OCORRENCIA_SAC.DS_TIPO_CLASSIFICACAO_SAC%TYPE;   
    V_LUCRO_PRODUTO FLOAT(10);
    V_SG_ESTADO MC_ESTADO.SG_ESTADO%TYPE;
    V_NM_ESTADO MC_ESTADO.NM_ESTADO%TYPE;
BEGIN

        

    
    FOR S IN SAC LOOP
  --pegando o sg_estado e o nm_estado. TA ESTRANHO ESTA COLETA, ACHO QUE TA TUDO ERRADO KKKK.  
        SELECT E.SG_ESTADO, E.NM_ESTADO 
        INTO V_SG_ESTADO, V_NM_ESTADO
        FROM MC_END_CLI EN INNER JOIN MC_LOGRADOURO L
            ON(EN.NR_CLIENTE = L.CD_LOGRADOURO)
            INNER JOIN MC_BAIRRO B 
            ON (L.CD_LOGRADOURO = B.CD_BAIRRO) 
            INNER JOIN MC_CIDADE C 
            ON (C.CD_CIDADE = B.CD_BAIRRO) 
            INNER JOIN MC_ESTADO E
            ON (E.SG_ESTADO = C.SG_ESTADO)
           WHERE S.NR_CLIENTE = EN.NR_CLIENTE;
            
            
            
    --TESTANDO O VALOR ARMAZENADO NA SG_ESTADO E NM_ESTADO        
            DBMS_OUTPUT.PUT_LINE('SG DO ESTADO: ' || V_SG_ESTADO);
            DBMS_OUTPUT.PUT_LINE('NM DO ESTADO: ' || V_NM_ESTADO);
            DBMS_OUTPUT.PUT_LINE('NR DO CLIENTE: ' || S.NR_CLIENTE);
    
    
    
    
    
    
    
    -- ATRIBUINDO O VALOR PARA O LUCRO DO PRODUTO
    V_LUCRO_PRODUTO := ROUND((S.VL_PERC_LUCRO /100) * S.VL_UNITARIO, 2);
    DBMS_OUTPUT.PUT_LINE('TESTE: ' || S.CD_PRODUTO || ' ' || V_LUCRO_PRODUTO);
    
--IF PRA VER QUAL É O TIPO DO SAC(DUVIDA, SUGESTÃO OU ELOGIO)
         IF  S.TP_SAC = 'D' THEN
             V_TP_SAC := 'DUVIDA';
         ELSIF S.TP_SAC = 'S' THEN
             V_TP_SAC := 'SUGESTAO';
         ELSIF S.TP_SAC = 'E' THEN
             V_TP_SAC := 'ELOGIO';
         ELSE
             V_TP_SAC := 'CLASSIFICACAO INVALIDA';
        
        END IF;
 --INSERINDO OS DADOS DA TABELA DE OCORRENCIA. "AINDA FALTA DADOS PARA SEREM INSERIDOS, EU PAREI NO LUCRO DO PRODUTO. FAVOR ANALISAR"
--             INSERT INTO MC_SGV_OCORRENCIA_SAC (NR_OCORRENCIA_SAC, DT_ABERTURA_SAC, HR_ABERTURA_SAC, DS_TIPO_CLASSIFICACAO_SAC, CD_PRODUTO, VL_UNITARIO_PRODUTO, 
   --                                             VL_PERC_LUCRO, VL_UNITARIO_LUCRO_PRODUTO, SG_ESTADO, NM_ESTADO, NR_CLIENTE, NM_CLIENTE, VL_ICMS_PRODUTO)
  --           VALUES(S.NR_SAC, S.DT_ABERTURA, S.HR_ABERTURA, V_TP_SAC, S.CD_PRODUTO, S.VL_UNITARIO, S.VL_PERC_LUCRO, V_LUCRO_PRODUTO, );
        
    END LOOP;

END;
/





--AQUI É SO ALGUNS SELECTS PRA EU VER O NOME DOS CAMPOS E A ESTRUTURA DAS TABELAS  PRA FAZER O CURSOR E O INSERT. 
DESC MC_SGV_OCORRENCIA_SAC;

    
SELECT * FROM MC_SGV_SAC;
SELECT * FROM MC_PRODUTO;
SELECT * FROM MC_CLIENTE;
SELECT * FROM MC_SGV_OCORRENCIA_SAC;
SELECT * FROM MC_ESTADO;
SELECT * FROM MC_END_CLI;
SELECT * FROM MC_LOGRADOURO;
SELECT * FROM MC_BAIRRO;
SELECT * FROM MC_CIDADE;
SELECT * FROM  MC_ESTADO;
